<html>
<head>
  <meta charset="UFT-8">
  <meta http-equiv="content-language" content="pt-br">
  <meta http-equiv="content-type" content="text/html; charset=UTF-8">
  <meta name="author" content="Claudiano Lima">
  <meta name="description" content="O Organize Pessoal é um gerenciador de 
  finanças e tarefas simples, muito poderoso e totalmente gratuito. Conte com 
  o Organize Pessoal, com ele você tem o controle de sua vida financeira e 
  pessoal.">
  <meta name="keywords" content="finanças, financeiro, controle, 
  gerenciamento de contas, gerenciamento financeiro, controle financeiro, 
  gerenciador de tarefas, controle pesoal">
  <meta name="robots" content="index, follow"> 
  <meta itemprop="name" content="Organize Pessoal - Organize sua vida de forma fácil">
  <meta itemprop="description" content="O Organize Pessoal é um gerenciador de 
  finanças e tarefas simples, muito poderoso e totalmente gratuito. Conte com 
  o Organize Pessoal, com ele você tem o controle de sua vida financeira e 
  pessoal.">
  <meta name="viewport" content="width=device-width, initial-scale=1, max-scale=1">

  <!-- Estilos CSS -->
  <link rel="stylesheet" type="text/css" href="/assets/css/styleNotFound.css">
  <link rel="stylesheet" type="text/css" href="/assets/css/styleGeral.css">

  <!-- Icon -->
  <link rel='icon' type="img/svg" href="/assets/images/iconLogo.svg">

  <!-- Title-->
  <title>Organize Pessoal - Seu gerenciador pessoal</title>
</head>
<body>
  <!-- Header -->
  <?php $this->importViews('header-home','notFound404') ?>

  <!-- Section -->
  <section class="sectionNotFound404One">
    <div class="container">
      <article class="sectionNotFound404OneInfo">
        <img src="/assets/images/notFound404.svg">
        <h3>
          Ops… Conteúdo indisponível no momento.
        </h3>
        <p>
          O conteúdo que você está tentando acessar infelizmente não exite ou 
          foi removido.
        </p>
        <div class="sectionNotFound404OneButton">
          <a href="/">Voltar a página principal</a>
        </div>
      </article>
    </div>
  </section>

  <!-- Footer -->
  <?php $this->footer('footer'); ?>

  <!-- jQuery e JavaScript -->
  <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
  <script src="/assets/js/scriptGeral.js"></script>
</body>
</html>