<html>
<head>
  <meta charset="UFT-8">
  <meta http-equiv="content-language" content="pt-br">
  <meta http-equiv="content-type" content="text/html; charset=UTF-8">
  <meta name="author" content="Claudiano Lima">
  <meta name="description" content="O Organize Pessoal é um gerenciador de 
  finanças e tarefas simples, muito poderoso e totalmente gratuito. Conte com 
  o Organize Pessoal, com ele você tem o controle de sua vida financeira e 
  pessoal.">
  <meta name="keywords" content="finanças, financeiro, controle, 
  gerenciamento de contas, gerenciamento financeiro, controle financeiro, 
  gerenciador de tarefas, controle pesoal">
  <meta name="robots" content="index, follow"> 
  <meta itemprop="name" content="Organize Pessoal - Organize sua vida de forma fácil">
  <meta itemprop="description" content="O Organize Pessoal é um gerenciador de 
  finanças e tarefas simples, muito poderoso e totalmente gratuito. Conte com 
  o Organize Pessoal, com ele você tem o controle de sua vida financeira e 
  pessoal.">
  <meta name="viewport" content="width=device-width, initial-scale=1, max-scale=1">

  <!-- Estilos CSS -->
  <link rel="stylesheet" type="text/css" href="/assets/css/styleConfirmar.css">
  <link rel="stylesheet" type="text/css" href="/assets/css/styleGeral.css">

  <!-- Icon -->
  <link rel='icon' type="img/svg" href="/assets/images/iconLogo.svg">

  <!-- Title-->
  <title>Confirme seu cadastro - Organize Pessoal</title>
</head>
<body>
  <!-- Header -->
  <?php $this->header('header-home','Confirmar') ?>

  <!-- Section -->
  <section class="sectionCadastroConfirmOne">
    <div class="container">
      <article class="sectionCadastroConfirmOneInfo">
        <img src="/assets/images/verifiedEmail.svg">
        <h3>
          Tudo pronto, é um prazer ter você como nosso cliente!
        </h3>
        <p>
          Bem-vindo(a) ao Organize pessoal, é um grande prazer ter você como 
          nosso cliente, vamos gerenciar de forma inteligente a vida para 
          aproveitar dela o que tem de melhor?
        </p>
      </article>
    </div>
  </section>


  <!-- Footer -->
  <?php $this->footer('footer'); ?>

  <!-- jQuery e JavaScript -->
  <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
  <script src="/assets/js/scriptGeral.js"></script>
</body>
</html>