<html>
<head>
  <meta charset="UFT-8">
  <meta http-equiv="content-language" content="pt-br">
  <meta http-equiv="content-type" content="text/html; charset=UTF-8">
  <meta name="author" content="Claudiano Lima">
  <meta name="description" content="O Organize Pessoal é um gerenciador de 
  finanças e tarefas simples, muito poderoso e totalmente gratuito. Conte com 
  o Organize Pessoal, com ele você tem o controle de sua vida financeira e 
  pessoal.">
  <meta name="keywords" content="finanças, financeiro, controle, 
  gerenciamento de contas, gerenciamento financeiro, controle financeiro, 
  gerenciador de tarefas, controle pesoal">
  <meta name="robots" content="index, follow"> 
  <meta itemprop="name" content="Organize Pessoal - Organize sua vida de forma fácil">
  <meta itemprop="description" content="O Organize Pessoal é um gerenciador de 
  finanças e tarefas simples, muito poderoso e totalmente gratuito. Conte com 
  o Organize Pessoal, com ele você tem o controle de sua vida financeira e 
  pessoal.">
  <meta name="viewport" content="width=device-width, initial-scale=1, max-scale=1">

  <!-- Estilos CSS -->
  <link rel="stylesheet" type="text/css" href="/assets/css/home/styleConfirmar.css">
  <link rel="stylesheet" type="text/css" href="/assets/css/styleGeral.css">

  <!-- Icon -->
  <link rel='icon' type="img/svg" href="/assets/images/iconLogo.svg">

  <!-- Title-->
  <title>Confirme seu cadastro - Organize Pessoal</title>
</head>
<body>
  <!-- loading -->
  <?php $this->importViews('loading') ?>
  
  <!-- Header -->
  <?php $this->importViews('header-home','Confirmar') ?>

  <!-- Section -->
  <section class="sectionConfirmarOne">
    <div class="container">
      <article class="sectionConfirmarOneInfo">
        <img src="/assets/images/home/confirmarEmail/confirmEmail.svg">
        <h3>
          Falta pouco, por favor confirme o seu cadastro.
        </h3>
        <p>
          Enviamos um link de confirmação para o seu e-mail. Acesse e siga as 
          instruções para confirmar o seu cadastro no Organize Pessoal. Se sua 
          caixa de mensagem não estiver contido o e-mail, por favor, verifique sua caixa de spam.
        </p>
      </article>
    </div>
  </section>

  <!-- Footer -->
  <?php $this->footer('footer'); ?>
  
</body>
</html>