<!DOCTYPE html>
<html>
  <head>
    <meta charset="UFT-8">
    <meta http-equiv="content-language" content="pt-br">
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta name="author" content="Claudiano Lima">
    <meta name="description" content="O Organize Pessoal é um gerenciador de 
    finanças e tarefas simples, muito poderoso e totalmente gratuito. Conte com 
    o Organize Pessoal, com ele você tem o controle de sua vida financeira e 
    pessoal.">
    <meta name="keywords" content="finanças, financeiro, controle, 
    gerenciamento de contas, gerenciamento financeiro, controle financeiro, 
    gerenciador de tarefas, controle pesoal">
    <meta name="robots" content="index, follow"> 
    <meta itemprop="name" content="Organize Pessoal - Organize sua vida de forma fácil">
    <meta itemprop="description" content="O Organize Pessoal é um gerenciador de 
    finanças e tarefas simples, muito poderoso e totalmente gratuito. Conte com 
    o Organize Pessoal, com ele você tem o controle de sua vida financeira e 
    pessoal.">

    <title>Organize Pessoal</title>
    <link rel='icon' type="img/svg" href="/assets/images/iconLogo.svg">
    <link rel="stylesheet" type="text/css" href="/assets/css/style.css">
    
  </head>
  <body>
  <?php $this->header('header-home') ?>

    <section class='sectionHomeOne'>
      <div class='container'>
        <div class="sectionHomeAreaDesc">
          <div class="sectionHomeTitle">
            Maneira simples de gerenciar suas finanças e sua vida pessoal.
          </div>
          <div class="sectionHomeDesc">
            Conte com o Organize Pessoal, com ele você tem o controle de sua vida 
            financeira e pessoal. Com o Organize Pessoal, você terá controle de 
            suas contas, suas tarefas e seus compromissos pessoais. Não precisa 
            mais de diversos aplicativos para gerência sua vida tão agitada. 
            Organize tudo em um só lugar!
          </div>
          <div class="sectionHomeButtonCadastrar">
            <a href="">Cadastra-se</a>
          </div>
        </div>
      </div>
    </section>

    <section class="sectionTwo">
      <div class='container'>
        <div class='sectionTwoTittle'>
          O que o Organize Pessoal pode lhe proporcionar?
        </div>
        <div class="sectionTwoDesc">
          O Organize Pessoal é uma ferramenta grátis de controle de gastos 
          pessoais e gerenciamento de tarefas que permite que você cadastre e 
          gerencie suas contas e tarefas de forma eficiente e prática.
        </div>
        <div class="sectionTwoCards">
          <div class="cards">
            <img src="assets/images/iconControle.svg">
            <div class='cardsTittle'>
              Controle seus gastos, é rápido e fácil.
            </div>
            <div class="cardsDesc">
              O site contém uma interface intuitiva e de fácil manipulação para 
              obter o controle de seus gastos, não necessita informa dados 
              pessoais como cartão de crédito ou conta bancária.
            </div>
          </div>
          <div class="cards">
            <img src="assets/images/iconDinheiro.svg">
            <div class='cardsTittle'>
              Acompanhe para onde o seu dinheiro vai.
            </div>
            <div class="cardsDesc">
              Evite as informações dos seus gastos espalhados em anotações, 
              extratos e planilhas. Tenha tudo em um só local, com gráficos e 
              relatórios de seus ganhos e despesas.
            </div>
          </div>

          <div class="cards">
            <img src="assets/images/iconAcompanha.svg">
            <div class='cardsTittle'>
              Acompanhe os seus ganhos mensais.
            </div>
            <div class="cardsDesc">
              Organizamos com gráficos e relatórios todos os seus recebimentos 
              mensais, não só o seu salário, mas também seus ganhos cotidianos, 
              como por exemplo.: Freelancer.
            </div>
          </div>

          <div class="cards">
            <img src="assets/images/iconAlert.svg">
            <div class='cardsTittle'>
              Alerta, nunca mais sofra com juros.
            </div>
            <div class="cardsDesc">
              Informamos a você quais contas estão prestes a vencer, com duas 
              semanas de antecedência. Assim não precisará se preocupar com 
              quais contas devem pagar e nem correr o risco de esquecer de 
              pagar alguma conta.
            </div>
          </div>

          <div class="cards">
            <img src="assets/images/iconOrganização.svg">
            <div class='cardsTittle'>
              Organize as suas tarefas cotidianas.
            </div>
            <div class="cardsDesc">
              Organize as suas tarefas do dia a dia. Assim você pode aproveitar 
              mais tempo com quem você gosta ou fazendo o que você gosta. 
              Lembramos a você as tarefas do dia a serem cumprida com um dia 
              de antecedência.
            </div>
          </div>

          <div class="cards">
            <img src="assets/images/iconTempo.svg">
            <div class='cardsTittle'>
              Tempo é dinheiro, assim  organizamos a sua vida.
            </div>
            <div class="cardsDesc big">
              Com a nossa plataforma, você vai organizar sua vida por completo. 
              Não só financeira, mas também cotidiana, a nossa plataforma 
              disponibiliza totalmente gratuito para você a ferramenta de 
              tarefas a fazerem, ganhos mensais e gastos mensais.
            </div>
          </div>
        </div>
      </div>
    </section>

    <section class="sectionThree">
      <div class="container">
        <div class="sectionThreeTitle">
          Ferramenta 100% gratuita. Cadastre e comece hoje mesmo a controlar 
          sua vida financeira e pessoal.
        </div>
        <div class="sectionThreeDesc">
          <div class="descLeft">
              Receber, pagar e realizar tarefas importantes é uma atividade muito 
              comum no cotidiano. Porém, quem leva uma vida agitada muitas vezes 
              esquecem de diversos compromissos importantes e o pior disso é que 
              acabam pagando muito caro por ter esquecido. Com isso surge a 
              plataforma Organize Pessoal, uma plataforma para lhe auxiliar na 
              sua vida cotidiana, que lembram dos seus deveres e suas contas, 
              sem deixar que você passe por constrangimento por esquece uma tarefa 
              importante ou pagar juros absurdos de boletos, cartão de crédito, 
              conta bancária e entre outros. Tenha tudo em um só local, gerencia 
              suas atividades e finanças em um só local e se livre de uma vez por 
              todas da perda de tempo gerenciando suas finanças e anotando as 
              atividades importantes.
            <div class="descLeftButton">
              <a href="">Cadastre-se</a>
            </div>
          </div>
          <div class="descright">
            <img src="assets/images/laptopPagina.svg">
          </div>
        </div>
      </div>
    </section>

    <section class="sectionFour">
      <div class="container">
        <div class="sectionFourIconHelp">
          <img src="assets/images/iconPerguntasFrequentes.svg">
        </div>
        <div class="sectionFourTitle">
          Perguntas frequentes:
        </div>
        <div class="sectionFourDesc">
          As principais dúvidas e respostas sobre o Organize Pessoal.
        </div>
        <div class='sectionFourHelps'>
          <div class="sectionFourHelpsCard">
            <div class="sectionFourHelpsTitle">
              a
            </div>
            <div class="sectionFourHelpsDesc">
  
            </div>
          </div>
        </div>
      </div>
    </section>

  </body>
</html>

