<html>
  <head>
    <meta charset="UFT-8">
    <meta http-equiv="content-language" content="pt-br">
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta name="author" content="Claudiano Lima">
    <meta name="description" content="O Organize Pessoal é um gerenciador de 
    finanças e tarefas simples, muito poderoso e totalmente gratuito. Conte com 
    o Organize Pessoal, com ele você tem o controle de sua vida financeira e 
    pessoal.">
    <meta name="keywords" content="finanças, financeiro, controle, 
    gerenciamento de contas, gerenciamento financeiro, controle financeiro, 
    gerenciador de tarefas, controle pesoal">
    <meta name="robots" content="index, follow"> 
    <meta itemprop="name" content="Organize Pessoal - Organize sua vida de forma fácil">
    <meta itemprop="description" content="O Organize Pessoal é um gerenciador de 
    finanças e tarefas simples, muito poderoso e totalmente gratuito. Conte com 
    o Organize Pessoal, com ele você tem o controle de sua vida financeira e 
    pessoal.">
    <meta name="viewport" content="width=device-width, initial-scale=1, max-scale=1">
    
    <!-- Estilos CSS -->
    <link rel="stylesheet" type="text/css" href="/assets/css/home/styleIndex.css">
    <link rel="stylesheet" type="text/css" href="/assets/css/styleGeral.css">
    
    <!-- Icon -->
    <link rel='icon' type="img/svg" href="/assets/images/iconLogo.svg">
    <title>Organize Pessoal - Seu gerenciador pessoal</title>
  </head>
  <body>
    <!-- loading -->
    <?php $this->importViews('loading') ?>

    <!-- Header -->
    <?php $this->importViews('header-home','Home') ?>

    <!-- Section -->
    <section class="sectionHomeOne">
      <img class="backgroundBottom" src="/assets/images/home/index/homeBackgroundBottom.svg">
      <div class="container">
        <div class='sectionHomeOneArea'>
          <article class='sectionHomeOneInfo'>
            <h2 id='homeTitleWriter'>
              Maneira simples de gerenciar suas finanças e sua vida pessoal.
            </h2>
            <div class='sectionHomeOneInfoDesc'>
              <p>
                Conte com o Organize Pessoal, com ele você tem o controle de sua vida 
                financeira e pessoal. Com o Organize Pessoal, você terá controle de 
                suas contas, suas tarefas e seus compromissos pessoais. Não precisa 
                mais de diversos aplicativos para gerência sua vida tão agitada. 
                Organize tudo em um só lugar!
              </p>
            </div>
            <div class="sectionHomeOneInfoDescButton">
              <a href="/cadastre-se">Cadastre-se</a>
            </div>
          </article>
          </div>
        </div>
      </div>
      <img class="homeBackgroundRight" src='/assets/images/home/index/homeBackgroundRight.svg' data-anime='right'>
    </section>

    <section>
      <div class="container">
        <article>
          <div class="sectionHomeTwoInfoTitle" data-anime='right'>
            <h2>O que o Organize Pessoal pode lhe proporcionar?</h2>
          </div>
          <div class="sectionHomeTwoInfoDesc" data-anime='left'>
            <h4>
              O Organize Pessoal é uma ferramenta grátis de controle de gastos 
              pessoais e gerenciamento de tarefas que permite que você cadastre e 
              gerencie suas contas e tarefas de forma eficiente e prática.
            <h4>
          </div>
        </article>
        <div class="sectionHomeTwoInfoCards">

          <article class="sectionHomeTwoCards" data-anime='depth'>
            <div class="sectionHomeTwoCardsImg">
              <img src="assets/images/home/index/iconControle.svg">
            </div>
            <h3>Controle seus gastos, é rápido e fácil.</h3>
            <p>
              O site contém uma interface intuitiva e de fácil manipulação para 
              obter o controle de seus gastos, não necessita informa dados 
              pessoais como cartão de crédito ou conta bancária.
            </p>
          </article>

          <article class="sectionHomeTwoCards" data-anime='depth'>
            <div class="sectionHomeTwoCardsImg">
              <img src="assets/images/home/index/iconDinheiro.svg">
            </div>
            <h3>Acompanhe para onde o seu dinheiro vai.</h3>
            <p>
              Evite as informações dos seus gastos espalhados em anotações, 
              extratos e planilhas. Tenha tudo em um só local, com gráficos e 
              relatórios de seus ganhos e despesas.
            </p>
          </article>

          <article class="sectionHomeTwoCards" data-anime='depth'>
            <div class="sectionHomeTwoCardsImg">
              <img src="assets/images/home/index/iconAcompanha.svg">
            </div>
            <h3>Acompanhe os seus ganhos mensais.</h3>
            <p>
              Organizamos com gráficos e relatórios todos os seus recebimentos 
              mensais, não só o seu salário, mas também seus ganhos cotidianos, 
              como por exemplo.: Freelancer.
            </p>
          </article>

          <article class="sectionHomeTwoCards" data-anime='depth'>
            <div class="sectionHomeTwoCardsImg">
              <img src="assets/images/home/index/iconAlert.svg">
            </div>
            <h3>Alerta, nunca mais sofra com juros.</h3>
            <p>
              Informamos a você quais contas estão prestes a vencer, com duas 
              semanas de antecedência. Assim não precisará se preocupar com 
              quais contas devem pagar e nem correr o risco de esquecer de 
              pagar alguma conta.
            </p>
          </article>

          <article class="sectionHomeTwoCards" data-anime='depth'>
            <div class="sectionHomeTwoCardsImg">
              <img src="assets/images/home/index/iconOrganização.svg">
            </div>
            <h3>Organize as suas tarefas cotidianas.</h3>
            <p>
              Organize as suas tarefas do dia a dia. Assim você pode aproveitar 
              mais tempo com quem você gosta ou fazendo o que você gosta. 
              Lembramos a você as tarefas do dia a serem cumprida com um dia 
              de antecedência.
            </p>
          </article>

          <article class="sectionHomeTwoCards" data-anime='depth'>
            <div class="sectionHomeTwoCardsImg">
              <img src="assets/images/home/index/iconTempo.svg">
            </div>
            <h3>Tempo é dinheiro, assim  organizamos a sua vida.</h3>
            <p>
              Você vai organizar sua vida por completo. Não só financeira, mas 
              também cotidiana, a nossa plataforma disponibiliza para você a 
              ferramenta de tarefas a fazerem, ganhos mensais e gastos mensais.
            </p>
          </article>
        </div>
      </div>
    </section>

    <section class="sectionHomeThree">
      <div class="container">
        <article class="sectionHomeThreeAreaTitle" data-anime='top'>
          <h2>
            Ferramenta 100% gratuita. Cadastre e comece hoje mesmo a controlar 
            sua vida financeira e pessoal.
          </h2>
        </article>
        <div class="sectionHomeThreeAreaInfo">
          <article class="sectionHomeThreeAreaInfoDesc" data-anime='left'>
            <h4>
              Receber, pagar e realizar tarefas importantes é uma atividade muito 
              comum no cotidiano. Porém, quem leva uma vida agitada muitas vezes 
              esquecem de diversos compromissos importantes e o pior disso é que 
              acabam pagando muito caro por ter esquecido. Com isso surge a 
              plataforma Organize Pessoal, uma plataforma para lhe auxiliar na 
              sua vida cotidiana, que lembram dos seus deveres e suas contas, 
              sem deixar que você passe por constrangimento por esquece uma tarefa 
              importante ou pagar juros absurdos de boletos, cartão de crédito, 
              conta bancária e entre outros. Tenha tudo em um só local, gerencia 
              suas atividades e finanças em um só local e se livre de uma vez por 
              todas da perda de tempo gerenciando suas finanças e anotando as 
              atividades importantes.
            </h4>
            <div>
              <a href="/cadastre-se">Cadastre-se</a>
            </div>
          </article>
          <div class="sectionHomeThreeAreaInfoImg" data-anime='right'>
            <img src="assets/images/home/index/laptopPagina.svg">
          </div>
          
        </div>
      </div>
    </section>

    <section class="sectionHomeFour">
      <div class="container">
        <div class="sectionHomeFourHelpIcon" data-anime='top'>
          <img src="assets/images/home/index/iconPerguntasFrequentes.svg">
        </div>
        <article class="sectionHomeFourInfo">
          <h2 data-anime='right'>
            Perguntas frequentes:
          </h2>
          <h4 data-anime='left'>
            As principais dúvidas e respostas sobre o Organize Pessoal.
          </h4>
        </article>

        <div class="sectionHomeFourHelps">
          <article class='sectionHomeFourHelp' data-anime='left'>
            <h4 class="hCollapseIcon iconPlus">
              O Organize Pessoal é gratuito ?
            </h4>
            <p class="hCollapse">
              Sim, o Organize Pessoal é totalmente gratuito e com ele você 
              pode organizar suas finanças e tarefas pessoais ao mesmo tempo, 
              tudo em um único lugar.<br><br>

              Na Organize Pessoal prezamos por ferramentas gratuitas para 
              ajudar no seu cotidiano, sua satisfação é a nossa maior 
              felicidade.
            </p>
          </article>

          <article class='sectionHomeFourHelp' data-anime='right'>
            <h4 class="hCollapseIcon iconPlus">
              O que fazer com o Organize Pessoal?
            </h4>
            <p class="hCollapse">
              Com o Organize Pessoal você pode gerenciar de forma fácil e 
              inteligente as suas finanças adicionando despesas dos cotidianos, 
              contas a pagar ou receber e suas tarefas cotidianas, ou seja, 
              com a Organize Pessoal você gerenciara a sua vida pessoal e 
              financeira.<br><br>

              Temos uma poderosa ferramenta de automação de controle tudo de 
              forma muito simples para que você não tenha dúvidas na hora de 
              usufruir do nosso sistema.<br><br>

              Com o Organize Pessoal, em seu painel você passa a ter acesso a 
              relatórios e gráficos incríveis além de ser notificado quando 
              uma conta ou uma tarefa está perto de se vencer.
            </p>
          </article>

          <article class='sectionHomeFourHelp' data-anime='left'>
            <h4 class="hCollapseIcon iconPlus">
              Não sou de maior, posso usar o Organize Pessoal?
            </h4>
            <p class="hCollapse">
              Sim, o Organize Pessoal não necessita de seus dados pessoais 
              como CPF, conta bancaria, cartão de crédito. Na Organize 
              Pessoal, você adiciona suas contas a pagar e receber e o 
              nosso sistema gerencia esses dados para lhe apresentar da 
              melhor forma possível, bem organizado e com gráficos dessas 
              despesas
            </p>
          </article>

          <article class='sectionHomeFourHelp' data-anime='right'>
            <h4 class="hCollapseIcon iconPlus">
              Como usar o Organize Pessoal?
            </h4>
            <p class="hCollapse">
              Para usar o Organize Pessoal é simples, basta se cadastra na 
              nossa plataforma e começar a cadastrar suas contas e 
              tarefas.<br><br>

              Detalhando contas rotineiras e recorrentes, todas com valor, 
              categorias e informações de controle. A partir disso nosso 
              sistema vai gerar automações e relatórios para te ajudar a 
              controlar.<br><br>

              Simples, fácil e gratuito!
            </p>
          </article>

          <article class='sectionHomeFourHelp' data-anime='left'>
            <h4 class="hCollapseIcon iconPlus">
              Precisa de documentos pessoais?
            </h4>
            <p class="hCollapse">
              Não, quando o sistema Organize Pessoal foi criado o intuito 
              principal era servir como uma ferramenta intuitiva, inteligente 
              e de fácil acesso, sem necessidade de expor seus documentos 
              pessoais como CPF, cartão de crédito e conta bancaria.<br><br>

              Sendo assim, você só precisa ter a iniciativa de inserir os 
              detalhamentos das contas a pagar ou a receber, no caso o tema, 
              descrição data. Mesma forma funciona para as listagens de 
              tarefas, você só necessita alimentar o sistema com os dados da 
              tarefa para que possa listar de forma inteligente, simples e 
              fácil
            </p>
          </article>

          <article class='sectionHomeFourHelp' data-anime='right'>
            <h4 class="hCollapseIcon iconPlus">
              De onde surgiu o Organize Pessoal?
            </h4>
            <p class="hCollapse">
              O Organize Pessoal surgiu com a ideia de juntar dois serviços 
                que é a financeira e a listagem de tarefas cotidianas para 
                ajudar as pessoas e a praticar os conhecimentos sobre 
                desenvolvimento Full Stack.<br><br>

                As ferramentas usadas nesse projeto foram HTML, CSS, JavaScript, 
                jQuery, Ajax e PHP. Foi desenvolvido inteiramente por Claudiano 
                Lima com o intuito de ganhar experiencia, atribuir como um de 
                seus projetos e disponibilizar esse serviço totalmente gratuito 
                para que as pessoas possam gerenciar sua vida de forma fácil e 
                rápido.
            </p>
          </article>
        </div>
      </div>
    </section>

    <!-- Footer -->
    <?php $this->footer('footer'); ?>

    <!-- jQuery e JavaScript -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="assets/js/scriptHome.js"></script>
    <script src='assets/js/scriptGeral.js'></script>
  </body>
</html>
