<!DOCTYPE html>
<html>
  <head>
    <title>Organize Pessoal</title>

    
  </head>
  <body>
    <section class='section-one'>
      <div class='container'>
        <div class="area-desc">
          <div class="section-title">
            Maneira simples de gerenciar suas finanças e sua vida pessoal.
          </div>
          <div class="section-desc">
            Conte com o Organize Pessoal, com ele você tem o controle de sua vida 
            financeira e pessoal. Com o Organize Pessoal, você terá controle de 
            suas contas, suas tarefas e seus compromissos pessoais. Não precisa 
            mais de diversos aplicativos para gerência sua vida tão agitada. 
            Organize tudo em um só lugar!
          </div>
          <div class="button-cadastrar">
            <a href="">Cadastra-se</a>
          </div>
        </div>
      </div>
    </section>

    <section class="section-two">
    </section>

  </body>
</html>

