<html>
<head>
  <meta charset="UFT-8">
  <meta http-equiv="content-language" content="pt-br">
  <meta http-equiv="content-type" content="text/html; charset=UTF-8">
  <meta name="author" content="Claudiano Lima">
  <meta name="description" content="O Organize Pessoal é um gerenciador de 
  finanças e tarefas simples, muito poderoso e totalmente gratuito. Conte com 
  o Organize Pessoal, com ele você tem o controle de sua vida financeira e 
  pessoal.">
  <meta name="keywords" content="finanças, financeiro, controle, 
  gerenciamento de contas, gerenciamento financeiro, controle financeiro, 
  gerenciador de tarefas, controle pesoal">
  <meta name="robots" content="index, follow"> 
  <meta itemprop="name" content="Organize Pessoal - Organize sua vida de forma fácil">
  <meta itemprop="description" content="O Organize Pessoal é um gerenciador de 
  finanças e tarefas simples, muito poderoso e totalmente gratuito. Conte com 
  o Organize Pessoal, com ele você tem o controle de sua vida financeira e 
  pessoal.">
  <meta name="viewport" content="width=device-width, initial-scale=1, max-scale=1">

  <!-- Estilos CSS -->
  <link rel="stylesheet" type="text/css" href="/assets/css/home/styleResetPassword.css">
  <link rel="stylesheet" type="text/css" href="/assets/css/styleGeral.css">

  <!-- Icon -->
  <link rel='icon' type="img/svg" href="/assets/images/iconLogo.svg">

  <!-- Title-->
  <title>Organize Pessoal - Seu gerenciador pessoal</title>
</head>
<body>
  <!-- loading -->
  <?php $this->importViews('loading') ?>
  
  <!-- Header -->
  <?php $this->importViews('header-home') ?>

  <!-- Section -->
  <section class="sectionResetPassword">
    <div class="container">
      <div class='sectionResetPasswordArea'>
        <h2>Redefinir senha</h2>
        <p></p>
        <div class="ResetPassword">
          <form>
            <div class="inputPassword">
              <label for='password'>
                <img src="/assets/images/home/login/loginSenha.svg"> Senha 
              </label>
              <input type="password" id="password" name="newPassword">
            </div>
            <div class="inputConfirmPassword">
            <label for="confirmPassword">
              <img src="/assets/images/home/login/loginSenha.svg">Confirmar Senha 
            </label>
            <input type="password" id="confirmPassword" name="confirmPassword">
            </div>
            <button>Redefinir Senha</button>
          </form>
        </div>
      </div>
    </div>
  </section>

  <!-- Footer -->
  <?php $this->footer('footer'); ?>

  <!-- jQuery e JavaScript -->
  <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
  <script src="/assets/js/scriptResetPassword.js"></script>
</body>
</html>