<html>
<head>
  <meta charset="UFT-8">
  <meta http-equiv="content-language" content="pt-br">
  <meta http-equiv="content-type" content="text/html; charset=UTF-8">
  <meta name="author" content="Claudiano Lima">
  <meta name="description" content="O Organize Pessoal é um gerenciador de 
  finanças e tarefas simples, muito poderoso e totalmente gratuito. Conte com 
  o Organize Pessoal, com ele você tem o controle de sua vida financeira e 
  pessoal.">
  <meta name="keywords" content="finanças, financeiro, controle, 
  gerenciamento de contas, gerenciamento financeiro, controle financeiro, 
  gerenciador de tarefas, controle pesoal">
  <meta name="robots" content="index, follow"> 
  <meta itemprop="name" content="Organize Pessoal - Organize sua vida de forma fácil">
  <meta itemprop="description" content="O Organize Pessoal é um gerenciador de 
  finanças e tarefas simples, muito poderoso e totalmente gratuito. Conte com 
  o Organize Pessoal, com ele você tem o controle de sua vida financeira e 
  pessoal.">
  <meta name="viewport" content="width=device-width, initial-scale=1, max-scale=1">

  <!-- Estilos CSS -->
  <link rel="stylesheet" type="text/css" href="/assets/css/home/styleSingup.css">
  <link rel="stylesheet" type="text/css" href="/assets/css/styleGeral.css">

  <!-- Icon -->
  <link rel='icon' type="img/svg" href="/assets/images/iconLogo.svg">

  <!-- Title-->
  <title>Organize Pessoal - Seu gerenciador pessoal</title>
</head>
<body>
  <!-- Header -->
  <?php $this->importViews('header-home','Cadastre-se') ?>

  <!-- Section -->
  <section class="sectionSingupOne">
    <div class='container'>
      <div class="sectionSingupOneAreaForm">
        <h2>Cadastre-se</h2>
        <h4>Já possui uma conta? <a href="/entrar">Fazer login!</a></h4>
        <div class="sectionSingupOneForm">
          <form action="" method="POST">
            <div class="inputBlock">
              <label for="nameUser">
                <img src="/assets/images/home/singup/singupIconName.svg"> 
                Nome:
              </label>
              <input type="text" id='nameUser' name='name'
              placeholder="Primeiro nome" >
            </div>
            
            <div class="inputBlock">
              <label for='surnameUser'>
                <img src="/assets/images/home/singup/singupIconSurname.svg"> 
                Sobrenome:
              </label>
              <input type="text" id="surnameUser" name="surname"
              placeholder="Informe segundo nome">
            </div>

            <div class="inputBlock">
              <label for='emailUser'>
                <img src="/assets/images/home/login/loginEmail.svg"> Email:
              </label>
              <input type="email" id="emailUser" name="email" 
              placeholder="Informe seu e-mail">
            </div>

            <div class="inputBlock">
              <label for="passwordUser">
                <img src="/assets/images/home/login/loginSenha.svg"> Senha:
              </label>
              <input type="password" id="passwordUser" name="senha"
              placeholder="Informe sua senha">
            </div>

            <button type="submit">Cadastrar</button>
          </form>
        </div>
      </div>
    </div>
    
  </section>

  <!-- Footer -->
  <?php $this->footer('footer'); ?>

  <!-- jQuery e JavaScript -->
  <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
  <script src="/assets/js/scriptGeral.js"></script>
</body>
</html>