<html>
<head>
  <meta charset="UFT-8">
  <meta http-equiv="content-language" content="pt-br">
  <meta http-equiv="content-type" content="text/html; charset=UTF-8">
  <meta name="author" content="Claudiano Lima">
  <meta name="description" content="O Organize Pessoal é um gerenciador de 
  finanças e tarefas simples, muito poderoso e totalmente gratuito. Conte com 
  o Organize Pessoal, com ele você tem o controle de sua vida financeira e 
  pessoal.">
  <meta name="keywords" content="finanças, financeiro, controle, 
  gerenciamento de contas, gerenciamento financeiro, controle financeiro, 
  gerenciador de tarefas, controle pesoal">
  <meta name="robots" content="index, follow"> 
  <meta itemprop="name" content="Organize Pessoal - Organize sua vida de forma fácil">
  <meta itemprop="description" content="O Organize Pessoal é um gerenciador de 
  finanças e tarefas simples, muito poderoso e totalmente gratuito. Conte com 
  o Organize Pessoal, com ele você tem o controle de sua vida financeira e 
  pessoal.">
  <meta name="viewport" content="width=device-width, initial-scale=1, max-scale=1">

  <!-- Estilos CSS -->
  <link rel="stylesheet" type="text/css" href="/assets/css/home/styleSobre.css">
  <link rel="stylesheet" type="text/css" href="/assets/css/styleGeral.css">

  <!-- Icon -->
  <link rel='icon' type="img/svg" href="/assets/images/iconLogo.svg">

  <!-- Title-->
  <title>Organize Pessoal - Seu gerenciador pessoal</title>
</head>
<body>
  <!-- Header -->
  <?php $this->importViews('header-home','Sobre') ?>

  <!-- Section -->
  <section class="sectionSobreOne">
    <div class="container">
      <article class="sectionSobreOneInfo">
        <h2 class="sectionSobreOneInfoTitle">
          Ferramenta totalmente gratuita para você gerenciar suas contas e 
          tarefas com o que tem de melhor.
        </h2>
        <h2 class="sectionSobreOneInfoSubTitle">
          Conheça um pouco sobre nós.
        </h2>
        <h4>
          O Organize Pessoal surgiu através de uma ideia de criar um sistema 
          para gerenciar as contas a pagar ou receber e as tarefas cotidianas, 
          tudo em um mesmo local para facilitar a vida dos usuários. Porque as 
          pessoas que usam sistemas para gerenciar sua vida financeira 
          geralmente usa agregado um sistema para gerenciar suas tarefas 
          cotidianas. Então foi aí que surgiu a ideia do Organize Pessoal, por 
          que não juntar o útil ao agradável e desenvolver um sistema que faça 
          os dois ao mesmo tempo, e no mesmo local, sem burocracia, dificuldade 
          e o melhor de tudo, totalmente gratuito? Então surge o Organize 
          Pessoal, o sistema completo para agregar e melhorar sua vida.<br><br>

          Além disso, o projeto tem como função de auxiliar na experiência do 
          criador Claudiano Lima, no que lhe concerne desenvolveu o Organize 
          Pessoal como um projeto pessoal para mostrar os seus conhecimentos 
          sobre desenvolvimento web full stack.
        </h4>
      </article>
    </div>
  </section>

  <!-- Footer -->
  <?php $this->footer('footer'); ?>

  <!-- jQuery e JavaScript -->
  <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
  <script src="/assets/js/scriptGeral.js"></script>
</body>
</html>