<html>
  <head>
    <meta charset="UFT-8">
    <meta http-equiv="content-language" content="pt-br">
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta name="author" content="Claudiano Lima">
    <meta name="description" content="O Organize Pessoal é um gerenciador de 
    finanças e tarefas simples, muito poderoso e totalmente gratuito. Conte com 
    o Organize Pessoal, com ele você tem o controle de sua vida financeira e 
    pessoal.">
    <meta name="keywords" content="finanças, financeiro, controle, 
    gerenciamento de contas, gerenciamento financeiro, controle financeiro, 
    gerenciador de tarefas, controle pesoal">
    <meta name="robots" content="index, follow"> 
    <meta itemprop="name" content="Organize Pessoal - Organize sua vida de forma fácil">
    <meta itemprop="description" content="O Organize Pessoal é um gerenciador de 
    finanças e tarefas simples, muito poderoso e totalmente gratuito. Conte com 
    o Organize Pessoal, com ele você tem o controle de sua vida financeira e 
    pessoal.">
    <meta name="viewport" content="width=device-width, initial-scale=1, max-scale=1">
    
    <!-- Estilos CSS -->
    <link rel="stylesheet" type="text/css" href="/assets/css/app/styleExpenses.css">
    <link rel="stylesheet" type="text/css" href="/assets/css/app/global/styleGlobal.css">
    <link rel="stylesheet" type="text/css" href="/assets/css/styleGeral.css">

    
    <!-- Icon -->
    <link rel='icon' type="img/svg" href="/assets/images/iconLogo.svg">
    <title>Organize Pessoal - Despesas</title>
  </head>
  <body>
    <!-- loading -->
    <?php $this->importViews('loading') ?>
  
    <!-- Header -->
    <?php $this->importViews('header-app') ?>

    <section>
      <div class="containerApp">
        <div class="sectionAppArea">
          <?php $this->importViews('menu-app', 'Expense') ?>

          <div class="sectionAppAreaRight">
            <div class="sectionAppOne">
              <h4 id='messege'></h4>
              <div class="sectionAppOneWallet">
                <?php $this->importViews('appWallet') ?>
              </div>
            </div>

            <div class='sectionAppExpenseFilter'>
              <div class="sectionAppExpenseFilterAreaLeft">

                <div class="sectionAppExpenseFilterContainer">
                  <div class="sectionAppExpenseFilterAll">
                    <div class="sectionAppExpenseFilterAllActive">
                      <h4>Todas despesas</h4>
                      <img src="/assets/images/app/appGlobal/dropDownFilter.svg">
                    </div>
                    <div class="sectionAppExpenseFilterAllNav">
                      <ul>
                        <li>Todas despesas</li>
                        <li>Fixas</li>
                        <li>Parcelada</li>
                        <li>Despesas Pagas</li>
                        <li>Despesas Não Pagas</li>
                      </ul>
                    </div>
                  </div>
                </div>

                <div class="sectionAppExpenseFilterContainer">
                  <div class="sectionAppExpenseFilterCategory">
                    <div class="sectionAppExpenseFilterCategoryActive">
                      <h4>Todas categorias</h4>
                      <img src="/assets/images/app/appGlobal/dropDownFilter.svg">
                    </div>
                    <div class="sectionAppExpenseFilterCategoryNav">
                      <ul>
                        <li>Todas categorias</li>
                        <li>Alimentação</li>
                        <li>Assinaturas e serviços</li>
                        <li>Casa</li>
                        <li>Compras</li>
                        <li>Cuidados pessoais</li>
                        <li>Dívidas e empréstimos</li>
                        <li>Educação</li>
                        <li>Entretenimento</li>
                        <li>Família e filhos</li>
                        <li>Impostos e Taxas</li>
                        <li>Investimentos</li>
                        <li>Mercado</li>
                        <li>Pets</li>
                        <li>Saúde</li>
                        <li>Trabalho</li>
                        <li>Transporte</li>
                        <li>Viagem</li>
                      </ul>
                    </div>
                  </div>
                </div>

                <div class="sectionAppExpenseFilterContainer">
                  <div class="sectionAppTwoFilterDadosDate">
                    <input type="text" name="month" data-mask="00/0000" 
                    placeholder="00/0000">
                  </div>
                </div>

                <div class="sectionAppExpenseFilterContainer">
                  <div class="sectionAppExpenseFilterButton" 
                  onclick="selectFilterExpense()">
                    <img src="/assets/images/app/expense/buttonFilter.svg">
                  </div>
                  <div class="sectionAppExpenseFilterButtonMobile" 
                  onclick="selectFilterExpense()">
                    <h4>Filtrar</h4>
                  </div>
                </div>
              </div>

              <div class="sectionAppExpenseThrow">
                <img src="/assets/images/app/appGlobal/iconPlus.svg">
                <h4>Lançar Despesa</h4>
              </div>
            </div>

            <?php 
              if(count($this->view->expenses) == 0) 
              { 
                $displayTable = 'none';
                $displayMessege = 'block';
              }
              else 
              {
                $displayTable = 'block';
                $displayMessege = 'none';
              }
            ?>

            <div class="sectionAppMessageExpense" 
            style="display: <?php echo $displayMessege; ?>;">
              <h3>
                Você não possui contas a pagar. Por favor, 
                comece agora a lançar as suas despesas.
              </h3>
            </div>
            
            <div class="sectionAppTable" 
            style="display: <?php echo $displayTable; ?>;">
              <article class="sectionAppTableTitle">
                <p class="desc">Descrição</p>
                <p class="date">Vencimento</p>
                <p class="category">Categoria</p>
                <p class="enrollment">Parcelas</p>
                <p class="price">Valor</p>
              </article>
              
              <?php foreach($this->view->expenses as $key => $value) {?>

                <article class="sectionAppTableItem" id='<?php echo $value['id'] ?>'>
                  <p class="desc">
                    <?php echo $value['description']?>
                  </p>
                  <p class="date">
                    <?php echo date_format(new DateTime($value['date']), 'd/m/Y');?>
                  </p>
                  <p class="category">
                    <?php echo $value['category']; ?>
                  </p>
                  <p class="enrollment">
                    <?php ; 
                        if($value['enrollment'] == 'Parcelada') {
                          echo $value['n_parcel_pay'].'/'.$value['n_parcel'];
                        }
                        else if($value['enrollment'] == 'Fixa') {
                          echo $value['status_parcel_fixed'];
                        }
                        else {
                          echo $value['enrollment'];
                        } 
                      ?>
                    </p>
                  <p class="price">
                    R$ <?php echo $value['value']; ?>
                    <!--
                      PENSAR EM COMO VAI FAZER PARA ALTERAR REMOVER E CONCLUIR, 
                      SE VAI SER POR AJAX OU LINK
                    -->
                    <img src="/assets/images/app/appGlobal/remove.svg"
                    onclick="removeExpense('<?php echo $value['id'] ?>')">
                    <img src="/assets/images/app/appGlobal/update.svg"
                    onclick="updateExpense('<?php echo $value['id'] ?>')">
                    <?php if($value['status'] == 0) {?>
                      <img src="/assets/images/app/appGlobal/conclude.svg"
                      onclick="concludeExpense('<?php echo $value['id'] ?>')">
                    <?php }?>
                  </p>
                </article>

              <?php } ?>
            </div>

            <div class="areaPayStatus">
              <div class="paidExpenses">
                <h4>Pagas: <?php 
                  echo("R$".$this->view->payments['ExpensesPayme']);
                  ?></h4>
              </div>
              <div class="payExpenses">
                <h4>A pagar: <?php 
                  echo("R$".$this->view->payments['ExpensesNotPayme']);
                  ?></h4>
              </div>
            </div>

          </div>
        </div>
      </div>
    </section>

    <!-- Modal de inserção de despesas -->
    <div class="newExpensesArea">
      <div class="newExpensesExit"></div>
      <div class="newExpensesForm">
        <article class="newExpensesFormTitle">
          <img src="/assets/images/app/appGlobal/iconTitleModal.svg">
          <h3>Adicionar despesa:</h3>
        </article>
        <p></p>

        <form>
          <article class="newExpensesLine">
            <label for='newExpensesDesc'>
              <img src="/assets/images/app/appGlobal/iconDescModal.svg"> Descição:
            </label>
            <input type="text" id='newExpensesDesc'
            placeholder="Ex: Investimento na bolsa de valor." name="Desc">
          </article>

          <div class="newExpensesLine">
            <article class="newExpensesValue">
              <label for="newExpensesValue">
                <img src="/assets/images/app/appGlobal/iconValueModal.svg"> Valor:
              </label>
              <input id='newExpensesValue' type="number" step="0.01" min="0.01" 
              placeholder="00.00R$" name="Value">
            </article>

            <article class="newExpensesDate">
              <label for="newExpensesDate">
                <img src="/assets/images/app/appGlobal/iconCalendarModal.svg"> Data:
              </label>
              <input type="date" id='newExpensesDate' placeholder="dd/mm/aaaa"
              name="Date">
            </article>
          </div>

          <div class="newExpensesLine">
            <article class="newExpensesWallet">
              <label for="newExpensesWallet">
                <img src="/assets/images/app/appGlobal/iconWalletModal.svg"> Carteira
              </label>
              <select id="newExpensesWallet" name="Wallet">
                <option value="">Carteiras</option>

                <?php
                  foreach($this->view->wallets as $key => $value) { ?>
                  
                    <option value="<?php echo $value['id'] ?>">
                      <?php echo $value['wallet_name']?>
                    </option>
                  
                <?php
                  }
                ?>

              </select>
            </article>

            <article class="newExpensesCategory">
              <label for="newExpensesCategory">
                <img src="/assets/images/app/appGlobal/iconCategoryModal.svg"> Categoria
              </label>
              <select id='newExpensesCategory' name="Category">
                <option value="">Categorias</option>
                <option value="Alimentação">Alimentação</option>
                <option value="Assinaturas e serviços">Assinaturas e serviços</option>
                <option value="Casa">Casa</option>
                <option value="Compras">Compras</option>
                <option value="Cuidados pessoais">Cuidados pessoais</option>
                <option value="Dívidas e empréstimos">Dívidas e empréstimos</option>
                <option value="Educação">Educação</option>
                <option value="Entretenimento">Entretenimento</option>
                <option value="Família e filhos">Família e filhos</option>
                <option value="Impostos e Taxas">Impostos e Taxas</option>
                <option value="Investimentos">Investimentos</option>
                <option value="Mercado">Mercado</option>
                <option value="Pets">Pets</option>
                <option value="Saúde">Saúde</option>
                <option value="Trabalho">Trabalho</option>
                <option value="Transporte">Transporte</option>
                <option value="Viagem">Viagem</option>
              </select>
            </article>
          </div>

          <div class="newExpensesLine">
            <article class="newExpensesRepetition">
              <label for="newExpensesRepetition">
                <img src="/assets/images/app/appGlobal/iconRepetitionModal.svg"> Repetição
              </label>
              <div class="expensesRepetitionSelects">
                <select class="enrollment" name="Repetition">
                  <option value=''>Repetições</option>
                  <option value='Única'>Única</option>
                  <option value='Fixa'>Fixa</option>
                  <option value='Parcelada'>Parcaleda</option>
                </select>
                <select class="fixed" name="RepetitionFixed">
                  <option value=''>Categorias fixas</option>
                  <option value='Mensal'>Mensal</option>
                  <option value='Anual'>Anual</option>
                </select>
                <input class='parcel' type="number" min="1" max="420"
                name='RepetitionParcel'>
              </div>
            </article>
          </div>

          <button>Lançar Despesa</button>

        </form>
      </div>
    </div>

    <div class="updateExpensesArea">
      <div class="updateExpensesExit"></div>
      <div class="updateExpensesForm">
        <article class="updateExpensesFormTitle">
          <img src="/assets/images/app/appGlobal/iconTitleModal.svg">
          <h3>Atualizar despesa:</h3>
        </article>
        <p></p>

        <form>
          <article class="updateExpensesLine">
            <label for='updateExpensesDesc'>
              <img src="/assets/images/app/appGlobal/iconDescModal.svg"> Descição:
            </label>
            <input type="text" id='updateExpensesDesc'
            placeholder="Ex: Investimento na bolsa de valor." name="expensesDesc">
          </article>

          <div class="updateExpensesLine">
            <article class="updateExpensesValue">
              <label for="updateExpensesValue">
                <img src="/assets/images/app/appGlobal/iconValueModal.svg"> Valor:
              </label>
              <input id='updateExpensesValue' type="number" step="0.01" min="0.01" 
              placeholder="00.00R$" name="expensesValue">
            </article>

            <article class="updateExpensesDate">
              <label for="updateExpensesDate">
                <img src="/assets/images/app/appGlobal/iconCalendarModal.svg"> Data:
              </label>
              <input type="date" id='updateExpensesDate' placeholder="dd/mm/aaaa"
              name="expensesDate">
            </article>
          </div>

          <div class="updateExpensesLine">
            <article class="updateExpensesWallet">
              <label for="updateExpensesWallet">
                <img src="/assets/images/app/appGlobal/iconWalletModal.svg"> Carteira
              </label>
              <select id="updateExpensesWallet" name="expensesWallet">
                <option value="">Carteiras</option>
                <option value="1">Carteira Geral</option>
                
                <?php
                  foreach($this->view->wallets as $key => $value) { ?>
                  
                    <option value="<?php echo $value['id'] ?>">
                      <?php echo $value['wallet_name']?>
                    </option>
                  
                <?php
                  }
                ?>
               
              </select>
            </article>

            <article class="updateExpensesCategory">
              <label for="updateExpensesCategory">
                <img src="/assets/images/app/appGlobal/iconCategoryModal.svg"> Categoria
              </label>
              <select id='updateExpensesCategory' name="receiveCategory">
                <option value="">Categorias</option>
                <option value="Alimentação">Alimentação</option>
                <option value="Assinaturas e serviços">Assinaturas e serviços</option>
                <option value="Casa">Casa</option>
                <option value="Compras">Compras</option>
                <option value="Cuidados pessoais">Cuidados pessoais</option>
                <option value="Dívidas e empréstimos">Dívidas e empréstimos</option>
                <option value="Educação">Educação</option>
                <option value="Entretenimento">Entretenimento</option>
                <option value="Família e filhos">Família e filhos</option>
                <option value="Impostos e Taxas">Impostos e Taxas</option>
                <option value="Investimentos">Investimentos</option>
                <option value="Mercado">Mercado</option>
                <option value="Pets">Pets</option>
                <option value="Saúde">Saúde</option>
                <option value="Trabalho">Trabalho</option>
                <option value="Transporte">Transporte</option>
                <option value="Viagem">Viagem</option>
              </select>
            </article>
          </div>

          <article class="updateExpensesLine">
            <label for="updateExpensesStatus">
              <img src="/assets/images/app/appGlobal/iconTitleModal.svg"> Categoria
            </label>
            <select id="updateExpensesStatus" name="updateExpensesStatus">
              <option value="0">Pendente</option>
              <option value="1">Concluída</option>
            </select>
          </article>

          <button>Atualizar Despesa</button>

        </form>
      </div>
    </div>

    <!-- jQuery e JavaScript -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="/assets/js/plugin/mask/jquery.mask.js"></script>

    <script src="/assets/js/scriptAppExpense.js"></script>
  </body>
</html>
