<?php
$dataDay = array();
for($i=1; $i<=31; $i++) {
  array_push($dataDay, $i);
}
//echo date('m');
?>
<html>
<head>
  <meta charset="UFT-8">
  <meta http-equiv="content-language" content="pt-br">
  <meta http-equiv="content-type" content="text/html; charset=UTF-8">
  <meta name="author" content="Claudiano Lima">
  <meta name="description" content="O Organize Pessoal é um gerenciador de 
  finanças e tarefas simples, muito poderoso e totalmente gratuito. Conte com 
  o Organize Pessoal, com ele você tem o controle de sua vida financeira e 
  pessoal.">
  <meta name="keywords" content="finanças, financeiro, controle, 
  gerenciamento de contas, gerenciamento financeiro, controle financeiro, 
  gerenciador de tarefas, controle pesoal">
  <meta name="robots" content="index, follow"> 
  <meta itemprop="name" content="Organize Pessoal - Organize sua vida de forma fácil">
  <meta itemprop="description" content="O Organize Pessoal é um gerenciador de 
  finanças e tarefas simples, muito poderoso e totalmente gratuito. Conte com 
  o Organize Pessoal, com ele você tem o controle de sua vida financeira e 
  pessoal.">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, max-scale=1.0">

  <!-- Estilos CSS -->
  <link rel="stylesheet" type="text/css" href="/assets/css/styleGeral.css">
  <link rel="stylesheet" type="text/css" href="/assets/css/app/styleHome.css">
  <link rel="stylesheet" type="text/css" href="/assets/css/app/global/styleGlobal.css">


  <!-- Script Chart.js -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js" 
  integrity="sha256-R4pqcOYV8lt7snxMQO/HSbVCFRPMdrhAFMH+vr9giYI=" 
  crossorigin="anonymous"></script>


  <!-- Icon -->
  <link rel='icon' type="img/svg" href="/assets/images/iconLogo.svg">

  <!-- Title-->
  <title>Organize Pessoal - Seu gerenciador pessoal</title>
</head>
<body>
  <!-- loading -->
  <?php $this->importViews('loading') ?>
  
  <!-- Header -->
  <?php $this->importViews('header-app', 'app') ?>

  <!-- Section -->
  <section class="sectionAppHomeOne">
    <div class="containerApp">
      <div class="sectionAppArea">
        <?php $this->importViews('menu-app', 'Home') ?>

        <div class="sectionAppHomeOneInfo">
          <div class="sectionAppHomeOneInfoHeader">
            <div class="sectionAppHomeOneInfoHeaderSale">

              <div class="sectionAppHomeOneInfoHeaderIcon">
                <img src="/assets/images/app/home/header/saleIcon.svg">
              </div>
              <div class="sectionAppHomeOneInfoHeaderSaleInfo">
                <h4>Saldo Atual</h4>
                <p>R$ 00,00</p>
              </div>

            </div>
            <div class="sectionAppHomeOneInfoHeaderReceive">

              <div class="sectionAppHomeOneInfoHeaderIcon">
                <img src="/assets/images/app/home/header/receiveIcon.svg">
              </div>
              <div class="sectionAppHomeOneInfoHeaderReceiveInfo">
                <h4>Receitas</h4>
                <p>R$ 00,00</p>
              </div>

            </div>
            <div class="sectionAppHomeOneInfoHeaderExpenses">

              <div class="sectionAppHomeOneInfoHeaderIcon">
                <img src="/assets/images/app/home/header/expenseIcon.svg">
              </div>
              <div class="sectionAppHomeOneInfoHeaderExpensesInfo">
                <h4>Despesas</h4>
                <p>R$ 00,00</p>
              </div>

            </div>
            <div class="sectionAppHomeOneInfoHeaderWallet">
              <?php $this->importViews('appWallet')?>
            </div>
          </div>

          <div class="sectionAppHomeOneInfoSection">
            <div class="sectionAppHomeOneInfoSectionReceive">

              <div class='sectionAppHomeOneInfoSectionReceiveTitle'>
                <img src='/assets/images/app/home/section/iconReceive.svg'>
                <h3>Receitas</h3>
              </div>

              <!-- Colocar aqui um operador logico que pergunta se a dados
                para colocar nas receitas a receber, se tiver ele não mostra 
                essa div e coloca as receitas, se não tiver, ele coloca a div e 
                não mostra as receitas-->
              <div class="sectionAppHomeOneInfoSectionNoRecive">
                <h4>Infelizmente, você não possui contas a receber.</h4>
              </div>

              <!-- 
              * Detalhes das Receitas
              -->
              <div class="sectionAppHomeOneInfoSectionReceiveNotification">
                <div class="sectionAppHomeOneInfoSectionNotificationDesc">
                  <h4>Descrição</h4>
                  <p>Em x dias</p>
                </div>
                <div class="sectionAppHomeOneInfoSectionReceiveNotificationValue">
                  <h4>R$ 00,00</h4>
                  <!-- Passar o id para uma função de onclick no javascript -->
                  <img src="/assets/images/app/home/section/iconSuccessReceive.svg"> 
                </div>
              </div>

              <div class="sectionAppHomeOneInfoSectionReceiveNotification">
                <div class="sectionAppHomeOneInfoSectionNotificationDesc">
                  <h4>Descrição</h4>
                  <p>Em x dias</p>
                </div>
                <div class="sectionAppHomeOneInfoSectionReceiveNotificationValue">
                  <h4>R$ 00,00</h4>
                  <!-- Passar o id para uma função de onclick no javascript -->
                  <img src="/assets/images/app/home/section/iconSuccessReceive.svg"> 
                </div>
              </div>
              <!-- 
              * Detalhes das Receitas
              -->

            </div>

            <div class="sectionAppHomeOneInfoSectionPay">
              <div class="sectionAppHomeOneInfoSectionPayTitle">
                <img src="/assets/images/app/home/section/iconPay.svg"> 
                <h3>Despesas</h3>
              </div>
              <!-- Colocar aqui um operador logico que pergunta se a dados
                para colocar nas receitas a receber, se tiver ele não mostra 
                essa div e coloca as receitas, se não tiver, ele coloca a div e 
                não mostra as receitas-->
              <div class="sectionAppHomeOneInfoSectionNoPay">
                <h4>Parabéns, no momento você não possui contas a pagar.</h4>
              </div>

              <!-- 
                * Detalhes das Despesas
              -->
              <div class="sectionAppHomeOneInfoSectionPayNotification">
                <div class="sectionAppHomeOneInfoSectionNotificationDesc">
                  <h4>Descrição</h4>
                  <p>Em x dias</p>
                </div>
                <div class="sectionAppHomeOneInfoSectionPayNotificationValue">
                  <h4>R$ 00,00</h4>
                  <!-- Passar o id para uma função de onclick no javascript -->
                  <img src="/assets/images/app/home/section/iconSuccessPay.svg">
                </div>
              </div>

              <div class="sectionAppHomeOneInfoSectionPayNotification">
                <div class="sectionAppHomeOneInfoSectionNotificationDesc">
                  <h4>Descrição</h4>
                  <p>Em x dias</p>
                </div>
                <div class="sectionAppHomeOneInfoSectionPayNotificationValue">
                  <h4>R$ 00,00</h4>
                  <!-- Passar o id para uma função de onclick no javascript -->
                  <img src="/assets/images/app/home/section/iconSuccessPay.svg">
                </div>
              </div>
              <!-- 
                * Detalhes das Despesas
              -->
            </div>

            <div class="sectionAppHomeOneInfoSectionTasks">
              <div class="sectionAppHomeOneInfoSectionTasksTitle">
                <img src="/assets/images/app/home/section/iconTasks.svg"> 
                <h3>Tarefas</h3>
              </div>
              <!-- Colocar aqui um operador logico que pergunta se a dados
                para colocar nas receitas a receber, se tiver ele não mostra 
                essa div e coloca as receitas, se não tiver, ele coloca a div e 
                não mostra as receitas-->
              <div class="sectionAppHomeOneInfoSectionNoTasks">
                <h4>Parabéns, no momento você não possui tarefas a concluírem.</h4>
              </div>

              <!-- 
                * Detalhes das Tarefas 
              -->
              <div class="sectionAppHomeOneInfoSectionTasksNotification">
                <div class="sectionAppHomeOneInfoSectionNotificationDesc">
                  <h4>Descrição da Tarefa</h4>
                  <p>Em x dias e x horas</p>
                </div>
                <!-- Passar o id para uma função de onclick no javascript -->
                <img src="/assets/images/app/home/section/iconSuccessTasks.svg">
              </div>

              <div class="sectionAppHomeOneInfoSectionTasksNotification">
                <div class="sectionAppHomeOneInfoSectionNotificationDesc">
                  <h4>Descrição da Tarefa</h4>
                  <p>Em x dias e x horas</p>
                </div>
                <!-- Passar o id para uma função de onclick no javascript -->
                <img src="/assets/images/app/home/section/iconSuccessTasks.svg">
              </div>
              <!-- 
                * /Detalhes das Tarefas 
              -->
            </div>
          </div>    
        </div>
      </div>
      <section class="sectionAppHomeOneInfoGraphic">
        <div class='sectionAppHomeOneInfoGraphicMessenger'>
          <h3>
          Caso o gráfico esteja de difícil visualização, por favor 
          rotacionar a tela do seu celular!
          </h3>
        </div>
        <div class="sectionAppHomeOneInfoGraphicGeneral">
          <div class="GraphicGeneral">
            <canvas id='GraphicGeneral'></canvas>
          </div>
          <script type="text/javascript">
            let ctx = document.getElementById('GraphicGeneral').getContext("2d");
            var graphic = new Chart(ctx, {
              type: 'line',
              data: {
                labels: [/*<?php echo implode(',', $dataDay); ?>*/],
                datasets: [{
                  label: 'Receita',
                  backgroundColor: "#34F06F",
                  borderColor: "#34F06F",
                  data: [/* Colocar os dados PHP */],
                  borderWidth: 2,
                  fill: false
                }, {
                  label: 'Despesa',
                  backgroundColor: "#E34E4E",
                  borderColor: "#E34E4E",
                  data: [/* Colocar os dados PHP */],
                  borderWidth: 2,
                  fill: false
                }] // datasets
              }, // data
              options: {
                title: {
                  display: true,
                  fontSize: 16,
                  text: 'Relatório mensal: Receitas x Despesas'
                }
              }
            });
          </script>
        </div>
        <div class="sectionAppHomeOneInfoGraphicDetailed">
          <div class="GraphicDetailed">
            <canvas id='GraphicDetailed'></canvas>
          </div>
          <script type="text/javascript">
            let GraphicDetailed = document.getElementById('GraphicDetailed').getContext("2d");
            var GraphicBar = new Chart(GraphicDetailed, {
              type: 'horizontalBar',
              data: {
                labels: ['Alimentação', 'Assinaturas e serviços','Casa',
                'Compras','Cuidados pessoais','Dívidas e empréstimos',
                'Educação','Entretenimento','Família e filhos',
                'Impostos e Taxas','Investimentos','Mercado','Pets','Saúde',
                'Trabalho','Transporte','Viagem'],
                datasets: [{
                  label: '',
                  backgroundColor: ["#D874A8","#C683E4","#8193E1","#F67CFF",
                  "#C657CE","#FF6C6C","#6470BA","#626491","#74E88B",
                  "#FF977C","#FF70A1","#FF8A72","#FFBE57","#72B4E1",
                  "#446FF5","#44BCE1","#E16B6B"],
                  data: [/* Colocar os dados PHP */]
                }] // datasets
              }, // data
              options: {
                title: {
                  display: true,
                  fontSize: 16,
                  text: 'Relatório despesas detalhadas'
                },
                layout: {
                  padding: {
                      left: 0,
                      right: 10,
                      top: 0,
                      bottom: 0
                  }
                }
              }
            })     
          </script>
        </div>
      </section>
      
    </div>
  </section>
</body>
</html>