<?php
$dataDay = array();
for($i=1; $i<=31; $i++) {
  array_push($dataDay, $i);
}

$peddingReceived = $this->view->pending['received'];
$peddingExpenses = $this->view->pending['expenses'];
$peddingTasks = $this->view->pending['tasks'];
?>
<html>
<head>
  <meta charset="UFT-8">
  <meta http-equiv="content-language" content="pt-br">
  <meta http-equiv="content-type" content="text/html; charset=UTF-8">
  <meta name="author" content="Claudiano Lima">
  <meta name="description" content="O Organize Pessoal é um gerenciador de 
  finanças e tarefas simples, muito poderoso e totalmente gratuito. Conte com 
  o Organize Pessoal, com ele você tem o controle de sua vida financeira e 
  pessoal.">
  <meta name="keywords" content="finanças, financeiro, controle, 
  gerenciamento de contas, gerenciamento financeiro, controle financeiro, 
  gerenciador de tarefas, controle pesoal">
  <meta name="robots" content="index, follow"> 
  <meta itemprop="name" content="Organize Pessoal - Organize sua vida de forma fácil">
  <meta itemprop="description" content="O Organize Pessoal é um gerenciador de 
  finanças e tarefas simples, muito poderoso e totalmente gratuito. Conte com 
  o Organize Pessoal, com ele você tem o controle de sua vida financeira e 
  pessoal.">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, max-scale=1.0">

  <!-- Estilos CSS -->
  <link rel="stylesheet" type="text/css" href="/assets/css/styleGeral.css">
  <link rel="stylesheet" type="text/css" href="/assets/css/app/styleHome.css">
  <link rel="stylesheet" type="text/css" href="/assets/css/app/global/styleGlobal.css">


  <!-- Script Chart.js -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js" 
  integrity="sha256-R4pqcOYV8lt7snxMQO/HSbVCFRPMdrhAFMH+vr9giYI=" 
  crossorigin="anonymous"></script>


  <!-- Icon -->
  <link rel='icon' type="img/svg" href="/assets/images/iconLogo.svg">

  <!-- Title-->
  <title>Organize Pessoal - Seu gerenciador pessoal</title>
</head>
<body>
  <!-- loading -->
  <?php $this->importViews('loading') ?>
  
  <!-- Header -->
  <?php $this->importViews('header-app', 'app') ?>

  <!-- Section -->
  <section class="sectionAppHomeOne">
    <div class="containerApp">
      <div class="sectionAppArea">
        <?php $this->importViews('menu-app', 'Home') ?>

        <div class="sectionAppHomeOneInfo">
          <div class="sectionAppHomeOneInfoHeader">
            <div class="sectionAppHomeOneInfoHeaderSale">

              <div class="sectionAppHomeOneInfoHeaderIcon">
                <img src="/assets/images/app/home/header/saleIcon.svg">
              </div>
              <div class="sectionAppHomeOneInfoHeaderSaleInfo">
                <h4>Saldo Atual</h4>
                <p>
                  R$<?php echo number_format($this->view->balanceDiff['diff'],2,",",".")?>
                </p>
              </div>

            </div>
            <div class="sectionAppHomeOneInfoHeaderReceive">

              <div class="sectionAppHomeOneInfoHeaderIcon">
                <img src="/assets/images/app/home/header/receiveIcon.svg">
              </div>
              <div class="sectionAppHomeOneInfoHeaderReceiveInfo">
                <h4>Receitas</h4>
                <p>
                  R$<?php echo $this->view->balanceDiff['sumReceived'] ?>
                </p>
              </div>

            </div>
            <div class="sectionAppHomeOneInfoHeaderExpenses">

              <div class="sectionAppHomeOneInfoHeaderIcon">
                <img src="/assets/images/app/home/header/expenseIcon.svg">
              </div>
              <div class="sectionAppHomeOneInfoHeaderExpensesInfo">
                <h4>Despesas</h4>
                <p>
                  R$<?php echo $this->view->balanceDiff['sumExpenses'] ?>
                </p>
              </div>

            </div>
            <div class="sectionAppHomeOneInfoHeaderWallet">
              <?php $this->importViews('appWallet')?>
            </div>
          </div>

          <div class="sectionAppHomeOneInfoSection">
            <div class="sectionAppHomeOneInfoSectionReceive">

              <div class='sectionAppHomeOneInfoSectionReceiveTitle'>
                <img src='/assets/images/app/home/section/iconReceive.svg'>
                <h3>Receitas</h3>
              </div>

              <?php if(count($peddingReceived) == 0) {?>

                <div class="sectionAppHomeOneInfoSectionNoRecive">
                  <h4>Infelizmente, você não possui contas a receber.</h4>
                </div>

              <?php 
              } 
              else {
                foreach ($peddingReceived as $key => $value) {
                  if($key == 10)
                  { 
                    break; 
                  }
                  $date = new \DateTime($value['date']);
                  $dateVerifc = new \DateTime(date('Y-m-d'));
                  $date >= $dateVerifc ? $class = 'pedding' : $class = 'late';
                  $diff = $date->diff($dateVerifc);
              ?>

                <div class="sectionAppHomeOneInfoSectionReceiveNotification">
                  <div class="sectionAppHomeOneInfoSectionNotificationDesc">
                    <h4>
                      <?php echo mb_strimwidth($value['description'],0,15,'…' ); ?>
                    </h4>
                    <p class='<?php echo $class ?>'>
                      <?php
                      if($class == 'pedding')
                      {
                        echo 'Em '.$diff->days.' dia(s)'; 
                      }
                      else
                      {
                        echo 'Há '.$diff->days.' dia(s)'; 
                      } 
                      ?>
                    </p>
                  </div>
                  <div class="sectionAppHomeOneInfoSectionReceiveNotificationValue">
                    <h4>
                      R$<?php echo number_format($value['value'],2,',','.')?>
                    </h4>
                    <img 
                    src="/assets/images/app/home/section/iconSuccessReceive.svg"
                    onclick="confirmed('received', <?php echo $value['id'] ?>)"> 
                  </div>
                </div>

              <?php 
                }
              }
              ?>

            </div>

            <div class="sectionAppHomeOneInfoSectionPay">
              <div class="sectionAppHomeOneInfoSectionPayTitle">
                <img src="/assets/images/app/home/section/iconPay.svg"> 
                <h3>Despesas</h3>
              </div>

              <?php if(count($peddingExpenses) == 0) {?>
              
                <div class="sectionAppHomeOneInfoSectionNoPay">
                  <h4>Parabéns, no momento você não possui contas a pagar.</h4>
                </div>
              
              <?php 
              } else {
                foreach ($peddingExpenses as $key => $value) {
                  if($key == 10) 
                  { 
                    break; 
                  }
                  $date = new \DateTime($value['date']);
                  $dateVerifc = new \DateTime(date('Y-m-d'));
                  $date >= $dateVerifc ? $class = 'pedding' : $class = 'late';
                  $diff = $date->diff($dateVerifc);
              ?>

                <div class="sectionAppHomeOneInfoSectionPayNotification">
                  <div class="sectionAppHomeOneInfoSectionNotificationDesc">
                    <h4>
                      <?php echo mb_strimwidth($value['description'],0,15,'…' ); ?>
                    </h4>
                    <p class='<?php echo $class ?>'>
                      <?php 
                      if($class == 'pedding')
                      {
                        echo 'Em '.$diff->days.' dia(s)'; 
                      }
                      else
                      {
                        echo 'Há '.$diff->days.' dia(s)'; 
                      } 
                      ?>
                    </p>
                  </div>
                  <div class="sectionAppHomeOneInfoSectionPayNotificationValue">
                    <h4>
                      R$<?php echo number_format($value['value'],2,',','.')?>
                    </h4>
                    <img 
                    src="/assets/images/app/home/section/iconSuccessPay.svg"
                    onclick="confirmed('expenses', <?php echo $value['id'] ?>)">
                  </div>
                </div>

              <?php 
                }
              }
              ?>
            </div>

            <div class="sectionAppHomeOneInfoSectionTasks">
              <div class="sectionAppHomeOneInfoSectionTasksTitle">
                <img src="/assets/images/app/home/section/iconTasks.svg"> 
                <h3>Tarefas</h3>
              </div>

              <?php if(count($peddingTasks) == 0) {?>

              <div class="sectionAppHomeOneInfoSectionNoTasks">
                <h4>Parabéns, no momento você não possui tarefas a concluírem.</h4>
              </div>
              <?php 
              } 
              else {
                foreach ($peddingTasks as $key => $value) {
                  if($key == 10)
                  { 
                    break; 
                  }
                  $date = new \DateTime($value['date']);
                  $dateVerifc = new \DateTime(date('Y-m-d'));
                  $date >= $dateVerifc ? $class = 'pedding' : $class = 'late';
                  $diff = $date->diff($dateVerifc);
              ?>

                <div class="sectionAppHomeOneInfoSectionTasksNotification">
                  <div class="sectionAppHomeOneInfoSectionNotificationDesc">
                    <h4>
                    <?php echo mb_strimwidth($value['description'],0,15,'…' ); ?>
                    </h4>
                    <p class='<?php echo $class ?>'>
                      <?php 
                      if($class == 'pedding')
                      {
                        echo 'Em '.$diff->days.' dia(s) as '.$date->format('H:m'); 
                      }
                      else
                      {
                        echo 'Há '.$diff->days.' dia(s) as '.$date->format('H:m'); 
                      }
                      ?> 
                    </p>
                  </div>
                  <img src="/assets/images/app/home/section/iconSuccessTasks.svg"
                  onclick="confirmed('tasks', <?php echo $value['id'] ?>)">
                </div>

              <?php 
                }
              }
              ?>
              
            </div>
          </div>    
        </div>
      </div>
      <section class="sectionAppHomeOneInfoGraphic">
        <div class='sectionAppHomeOneInfoGraphicMessenger'>
          <h3>
          Caso o gráfico esteja de difícil visualização, por favor 
          rotacionar a tela do seu celular!
          </h3>
        </div>
        <div class="sectionAppHomeOneInfoGraphicGeneral">
          <div class="GraphicGeneral">
            <canvas id='GraphicGeneral'></canvas>
          </div>
        </div>
        <div class="sectionAppHomeOneInfoGraphicDetailed">
          <div class="GraphicDetailed">
            <canvas id='GraphicDetailed'></canvas>
          </div>
        </div>
      </section>
      
    </div>
  </section>

  <!-- jQuery e JavaScript -->
  <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
  <script src="/assets/js/scriptAppHome.js"></script>
</body>
</html>