<!DOCTYPE html>
<html>
  <head>
    <meta charset="UFT-8">
    <meta http-equiv="content-language" content="pt-br">
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta name="author" content="Claudiano Lima">
    <meta name="description" content="O Organize Pessoal é um gerenciador de 
    finanças e tarefas simples, muito poderoso e totalmente gratuito. Conte com 
    o Organize Pessoal, com ele você tem o controle de sua vida financeira e 
    pessoal.">
    <meta name="keywords" content="finanças, financeiro, controle, 
    gerenciamento de contas, gerenciamento financeiro, controle financeiro, 
    gerenciador de tarefas, controle pesoal">
    <meta name="robots" content="index, follow"> 
    <meta itemprop="name" content="Organize Pessoal - Organize sua vida de forma fácil">
    <meta itemprop="description" content="O Organize Pessoal é um gerenciador de 
    finanças e tarefas simples, muito poderoso e totalmente gratuito. Conte com 
    o Organize Pessoal, com ele você tem o controle de sua vida financeira e 
    pessoal.">
    <meta name="viewport" content="width=device-width, initial-scale=1, max-scale=1">
    
    <!-- Estilos CSS -->
    <link rel="stylesheet" type="text/css" href="/assets/css/app/styleProfile.css">
    <link rel="stylesheet" type="text/css" href="/assets/css/styleGeral.css">
    <link rel="stylesheet" type="text/css" href="/assets/css/app/global/styleGlobal.css">
    
    <!-- Icon -->
    <link rel='icon' type="img/svg" href="/assets/images/iconLogo.svg">
    <title>Organize Pessoal - Perfil</title>
  </head>
  <body>
    <!-- loading -->
    <?php $this->importViews('loading') ?>
  
    <!-- Header -->
    <?php $this->importViews('header-app') ?>

    <section>
      <div class="containerApp">
        <div class="sectionAppArea">
          <?php $this->importViews('menu-app', 'Profile') ?>

          <div class="sectionAppAreaRight">
            <div class='sectionAppProfileArea'>
              <!-- 
                Adicionar a action para a rota do backend, só o modal que vai 
                ser através do ajax
              -->
              <form method="POST">
                <div class="appProfileData">
                  <div class="appProfileName">
                    <label for="userName">Nome:</label><br>
                    <!-- Adicionar o nome do usuário através do php-->
                    <input type="text" id="userName" name="name" value="">
                  </div>
                  <div class="appProfileSurname">
                    <label for="userSurname">Sobrenome:</label><br>
                    <!-- Adicionar o sobrenome do usuário através do php-->
                    <input type="text" id="userSurname" name="surname" value="">
                  </div>
                </div>
                <div class="appProfileData">
                  <div class="appProfileGender">
                    <div class="appProfileGenderSelect">
                      <label for="userGender">Gênero</label><br>
                      <input type="text" id="userGender" name="gender" value="Selecionar" Readonly> 
                    </div>
                    <div class="appProfileGenderNav">
                      <ul>
                        <li>Masculino</li>
                        <li>Feminino</li>
                      </ul>
                    </div>
                  </div>
                </div>
                <div class="appProfileData">
                  <div class="appProfileBirth">
                    <label for="userBirth">Nascimento:</label><br>
                    <input type="date" id="userBirth" name="birth">
                  </div>
                  <div class="appProfileEmail">
                    <label for="userEmail">Email:</label><br>
                    <input type="email" id="userEmail" name="email">
                  </div>
                </div>
                <div class="appProfileData">
                  <div class="appProfilePassword">
                    <label for="appProfilePassword">Senha:</label><br>
                    <input type="password" id="appProfilePassword" name="password">
                  </div>
                  <div class="appProfileConfirmPassword">
                    <label for="appProfileConfirmPassword">Confirmar senha:</label><br>
                    <input type="password" id="appProfileConfirmPassword" name="confirmPassword">
                  </div>
                </div>
                <div class="appProfileButton">
                  <div class="appProfileButtonUpdate">
                    <button type="submit">Atualizar</button>
                  </div>
                  <div class='appProfileButtonUpdatePassword'>
                    Alterar minha senha
                  </div>
                </div>
              </form>
            </div>

          </div>
        </div>
      </div>
    </section>

    <!-- jQuery e JavaScript -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="/assets/js/scriptAppProfile.js"></script>
  </body>
</html>
