<!DOCTYPE html>
<html>
  <head>
    <meta charset="UFT-8">
    <meta http-equiv="content-language" content="pt-br">
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta name="author" content="Claudiano Lima">
    <meta name="description" content="O Organize Pessoal é um gerenciador de 
    finanças e tarefas simples, muito poderoso e totalmente gratuito. Conte com 
    o Organize Pessoal, com ele você tem o controle de sua vida financeira e 
    pessoal.">
    <meta name="keywords" content="finanças, financeiro, controle, 
    gerenciamento de contas, gerenciamento financeiro, controle financeiro, 
    gerenciador de tarefas, controle pesoal">
    <meta name="robots" content="index, follow"> 
    <meta itemprop="name" content="Organize Pessoal - Organize sua vida de forma fácil">
    <meta itemprop="description" content="O Organize Pessoal é um gerenciador de 
    finanças e tarefas simples, muito poderoso e totalmente gratuito. Conte com 
    o Organize Pessoal, com ele você tem o controle de sua vida financeira e 
    pessoal.">
    <meta name="viewport" content="width=device-width, initial-scale=1, max-scale=1">
    
    <!-- Estilos CSS -->
    <link rel="stylesheet" type="text/css" href="/assets/css/app/styleReceive.css">
    <link rel="stylesheet" type="text/css" href="/assets/css/styleGeral.css">
    <link rel="stylesheet" type="text/css" href="/assets/css/app/global/styleGlobal.css">
    
    <!-- Icon -->
    <link rel='icon' type="img/svg" href="/assets/images/iconLogo.svg">
    <title>Organize Pessoal - Receitas</title>
  </head>
  <body>
    <!-- loading -->
    <?php $this->importViews('loading') ?>
  
    <!-- Header -->
    <?php $this->importViews('header-app') ?>

    <section>
      <div class="containerApp">
        <div class="sectionAppArea">
          <?php $this->importViews('menu-app', 'Receive') ?>

          <div class="sectionAppAreaRight">
            <div class="sectionAppOne">
              <div id="messege"></div>
              <div class="sectionAppOneWallet">
                <?php $this->importViews('appWallet', 'Receive') ?>
              </div>
            </div>
  
            <div class="sectionAppTwo">
              <div class="sectionAppTwoFilter">

                <div class="sectionAppTwoFilterContainer">
                  <div class="sectionAppTwoFilterDadosReceive">
                    <div class="sectionAppTwoFilterActiveReceive">
                      <h4 class="select">Receitas</h4>
                      <img src="/assets/images/app/appGlobal/dropDownFilter.svg">
                    </div>
                    <div class="sectionAppTwoFilterNavReceive">
                      <ul>
                        <li>Receitas</li>
                        <li>Receitas Recebidas</li>
                        <li>Receitas Não Recebidas</li>
                      </ul>
                    </div>
                  </div>
                </div>
                
                <div class='sectionAppTwoFilterContainer'>
                  <div class="sectionAppTwoFilterDadosCategory">
                    <div class="sectionAppTwoFilterActiveCategory">
                      <h4 class="select">Categoria</h4>
                      <img src="/assets/images/app/appGlobal/dropDownFilter.svg">
                    </div>
                    <div class="sectionAppTwoFilterNavCategory">
                      <ul>
                        <li>Categoria</li>
                        <li>Salário</li>
                        <li>Empréstimo</li>
                        <li>Outras Receitas</li>
                      </ul>
                    </div>
                  </div>
                </div>
                <div class='sectionAppTwoFilterContainer'>
                  <div class="sectionAppTwoFilterDadosDate">
                    <input type="text" name="month" data-mask="00/0000" placeholder="00/0000">
                  </div>
                </div>


                <div class="sectionAppTwoFilterContainer">
                  <div class="sectionAppTwoFilterSubmite" onclick="sectionAppFilter()">
                    <img src="/assets/images/app/receive/buttonFilter.svg">
                  </div>
                  <div class='sectionAppTwoFilterSubmiteMobile' onclick="sectionAppFilter()">
                    <h4>Filtrar</h4>
                  </div>
                </div>
              </div>
              
              <div class="sectionAppTwoRecive">
                <img src="/assets/images/app/appGlobal/iconPlus.svg"> 
                <h4>Lançar Receitas</h4>
              </div>
            </div>

            
            
            <!-- 
              * LÓGICA PHP
            -->
            <?php 
              if(count($this->view->receives) == 0) {
            ?>

              <div class="sectionAppThreeMessage">
                <h3>
                  Você não possui contas a receber. Por favor, comece agora 
                  a lançar as suas receitas.
                </h3>
              </div>
              
            <?php
              } 
            ?>
              <div class="sectionAppTable">
                <article class="sectionAppTableTitle">
                  <p class="desc">Descrição</p>
                  <p class="date">Vencimento</p>
                  <p class="category">Categoria</p>
                  <p class="enrollment">Parcelas</p>
                  <p class="price">Valor</p>
                </article>
                <?php foreach($this->view->receives as $key => $value) {?>
                  <article class="sectionAppTableItem" id='<?php echo $value['id'] ?>'>
                    <p class="desc">
                      <?php echo $value['description']?>
                    </p>
                    <p class="date">
                      <?php echo date_format(new DateTime($value['date']), 'd/m/Y');?>
                    </p>
                    <p class="category">
                      <?php echo $value['category']; ?>
                    </p>
                    <p class="enrollment">
                      <?php ; 
                        if($value['enrollment'] == 'Parcelada') {
                          echo $value['n_parcel_pay'].'/'.$value['n_parcel'];
                        }
                        else if($value['enrollment'] == 'Fixa') {
                          echo $value['status_parcel_fixed'];
                        }
                        else {
                          echo $value['enrollment'];
                        } 
                      ?>
                    </p>
                    <p class="price">
                      R$<?php echo $value['value']; ?>
                      <!--
                        PENSAR EM COMO VAI FAZER PARA ALTERAR REMOVER E CONCLUIR, 
                        SE VAI SER POR AJAX OU LINK
                      -->
                      <img src="/assets/images/app/appGlobal/remove.svg"
                      onclick="removeReceived('<?php echo $value['id'] ?>')">
                      <img src="/assets/images/app/appGlobal/update.svg"
                      onclick="updateReceived('<?php echo $value['id'] ?>')">
                      <?php if($value['status'] == 0) {?>

                        <img src="/assets/images/app/appGlobal/conclude.svg"
                        onclick="concludeReceived('<?php echo $value['id'] ?>')">
                        
                      <?php } ?>
                    </p>
                  </article>
                <?php 
                  }
                ?>
              </div>

              <div class='areaPayStatus'>
              <div class="payReceived">
                <h4>
                  Recebido: <?php 
                  echo("R$".$this->view->payments['paymentReceived']);
                  ?>
                </h4>
              </div>
              <div class="payReceivable">
                <h4>
                  A receber: <?php 
                  echo("R$".$this->view->payments['paymentNotReceived']);
                  ?>
                </h4>
              </div>
            </div>

            

          </div>
          

          

        </div>
      </div>
    </section>
    
    


    <div class='newReceiveArea'>
      <div class="newReceiveFormExit"></div>
      <div class="newReceiveForm">
        <div class="newReceiveFormTitle">
          <img src="/assets/images/app/appGlobal/iconTitleModal.svg">
          <h3>Adicionar receita:</h3>
        </div>
        <p></p>
        <form>
          <div class="newReceiveLine">
            <label for="newReceiveDesc">
              <img src="/assets/images/app/appGlobal/iconDescModal.svg"> Descição:
            </label>
            <input type="text" id='newReceiveDesc'
            placeholder="Ex: Investimento na bolsa de valor." name="receiveDesc">
          </div>
          <div class="newReceiveLine">
            <div class="newReceiveValue">
              <label for="newReceiveDesc">
                <img src="/assets/images/app/appGlobal/iconValueModal.svg"> Valor:
              </label>
              <input type="number" step="0.01" min="0.01" 
              placeholder="00.00R$" name="receiveValue">
            </div>

            <div class="newReceiveDate">
              <label for="newReceiveDate">
                <img src="/assets/images/app/appGlobal/iconCalendarModal.svg"> Data:
              </label>
              <input type="date" id='newReceiveDate' placeholder="dd/mm/aaaa"
              name="receiveDate">
            </div>
          </div>
          <div class="newReceiveLine">
            <div class="newReceiveWallet">
              <label for="newReceiveWallet">
                <img src="/assets/images/app/appGlobal/iconWalletModal.svg"> Carteira
              </label>
              <select name="receiveWallet">
                <option value=""></option>
                <?php
                  foreach($this->view->wallets as $key => $value) { ?>
                  
                    <option value="<?php echo $value['id'] ?>">
                      <?php echo $value['wallet_name']?>
                    </option>
                  
                  <?php
                  }
                  ?>
                
              </select>
            </div>

            <div class="newReceiveCategory">
              <label for="newReceiveCategory">
                <img src="/assets/images/app/appGlobal/iconCategoryModal.svg"> Categoria
              </label>
              <select name="receiveCategory">
                <option value="">Categorias</option>
                <option value="Salário">Salário</option>
                <option value="Empréstimo">Empréstimo</option>
                <option value="Outras Receitas">Outras Receitas</option>
              </select>
            </div>
          </div>
          <div class="newReceiveLine">
            <div class="newReceiveRepetition">
              <label for="newReceiveRepetition">
                <img src="/assets/images/app/appGlobal/iconRepetitionModal.svg"> Repetição
              </label>
              <div class="receiveRepetitionSelects">
                <select class="enrollment" name="receiveRepetition">
                  <option value=''>Repetições</option>
                  <option value='Única'>Única</option>
                  <option value='Fixa'>Fixa</option>
                  <option value='Parcelada'>Parcaleda</option>
                </select>
                <select class="fixed" name="receiveRepetitionFixed">
                  <option value=''>Categorias fixas</option>
                  <option value='Mensal'>Mensal</option>
                  <option value='Anual'>Anual</option>
                </select>
                <input class='parcel' type="number" min="1" max="420"
                name='receiveRepetitionParcel'>
              </div>
            </div>
          </div>


          <button>Lançar Receita</button>
        </form>
      </div>
    </div>

    <!-- jQuery e JavaScript -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="/assets/js/plugin/mask/jquery.mask.js"></script>

    <script src="/assets/js/scriptAppReceive.js"></script>
  </body>
</html>
