<html>
  <head>
    <meta charset="UFT-8">
    <meta http-equiv="content-language" content="pt-br">
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta name="author" content="Claudiano Lima">
    <meta name="description" content="O Organize Pessoal é um gerenciador de 
    finanças e tarefas simples, muito poderoso e totalmente gratuito. Conte com 
    o Organize Pessoal, com ele você tem o controle de sua vida financeira e 
    pessoal.">
    <meta name="keywords" content="finanças, financeiro, controle, 
    gerenciamento de contas, gerenciamento financeiro, controle financeiro, 
    gerenciador de tarefas, controle pesoal">
    <meta name="robots" content="index, follow"> 
    <meta itemprop="name" content="Organize Pessoal - Organize sua vida de forma fácil">
    <meta itemprop="description" content="O Organize Pessoal é um gerenciador de 
    finanças e tarefas simples, muito poderoso e totalmente gratuito. Conte com 
    o Organize Pessoal, com ele você tem o controle de sua vida financeira e 
    pessoal.">
    <meta name="viewport" content="width=device-width, initial-scale=1, max-scale=1">
    
    <!-- Estilos CSS -->
    <link rel="stylesheet" type="text/css" href="/assets/css/app/styleTasks.css">
    <link rel="stylesheet" type="text/css" href="/assets/css/app/global/styleGlobal.css">
    <link rel="stylesheet" type="text/css" href="/assets/css/styleGeral.css">

    
    <!-- Icon -->
    <link rel='icon' type="img/svg" href="/assets/images/iconLogo.svg">
    <title>Organize Pessoal - Despesas</title>
  </head>
  <body>
    <!-- loading -->
    <?php $this->importViews('loading') ?>
  
    <!-- Header -->
    <?php $this->importViews('header-app') ?>

    <section>
      <div class="containerApp">
        <div class="sectionAppArea">
          <?php $this->importViews('menu-app', 'Tasks') ?>

          <div class="sectionAppAreaRight">
            <div class="sectionAppOne">
              <div id="messege"></div>
              <div class="sectionAppOneWallet">
                <?php $this->importViews('appWallet') ?>
              </div>
            </div>

            <div class='sectionAppTasksFilter'>
              <div class="sectionAppTasksFilterAreaLeft">

                <div class="sectionAppTasksFilterContainer">
                  <div class="sectionAppTasksFilterAll">
                    <div class="sectionAppTasksFilterAllActive">
                      <h4>Todas tarefas</h4>
                      <img src="/assets/images/app/appGlobal/dropDownFilter.svg">
                    </div>
                    <div class="sectionAppTasksFilterAllNav">
                      <ul>
                        <li>Todas tarefas</li>
                        <li>Tarefas concluídas</li>
                        <li>Tarefas pendentes</li>
                      </ul>
                    </div>
                  </div>
                </div>
                <div class='sectionAppTasksFilterContainer'>
                  <article class='sectionAppTwoFilterDadosDate'>
                    <input type="text" name="month" data-mask="00/0000" 
                    placeholder="00/0000">
                  </article>
                </div>

                <div class="sectionAppTasksFilterContainer">
                  <div class="sectionAppTasksFilterButton" 
                  onclick="selectFilterTasks()">
                    <img src="/assets/images/app/tasks/buttonFilter.svg">
                  </div>
                  <div class="sectionAppTasksFilterButtonMobile" 
                  onclick="selectFilterTasks()">
                    <h4>Filtrar</h4>
                  </div>
                </div>
              </div>

              <div class="sectionAppTasksThrow">
                <img src="/assets/images/app/appGlobal/iconPlus.svg">
                <h4>Nova Tarefa</h4>
              </div>
            </div>

            <?php 
              if(count($this->view->tasks) == 0) 
              { 
                $displayTable = 'none';
                $displayMessege = 'block';
              }
              else 
              {
                $displayTable = 'block';
                $displayMessege = 'none';
              }
            ?>

            <div class="sectionAppMessageTasks"
            style="display: <?php echo $displayMessege; ?>;">
              <h3>
                Você não possui tarefas. Por favor, 
                comece agora adicionar suas tarefas.
              </h3>
            </div>
            
  
            

            <!--
              * CASO NÃO ESTIVER VAZIA, IMPRIMIR A TABELA E PREENCHER A TABELA
            -->
            <div class="sectionAppTableTasks"
            style="display: <?php echo $displayTable; ?>;">
              <article class="sectionAppTableTitleTasks">
                <p class="desc">Descrição</p>
                <p class="date">Data - Hora</p>
              </article>

              <?php foreach($this->view->tasks as $key => $value) {?>
              
                <article class="sectionAppTableItemTasks">
                  <p class="desc">
                    <?php echo $value['description']?>
                  </p>
                  <p class="date">
                  <?php echo date_format(new DateTime($value['date']), 'd/m/Y H:i');?>
                    <!--
                      PENSAR EM COMO VAI FAZER PARA ALTERAR REMOVER E CONCLUIR, 
                      SE VAI SER POR AJAX OU LINK
                    -->
                    <span>
                      <img src="/assets/images/app/appGlobal/remove.svg"
                      onclick="removeTasks('<?php echo $value['id'] ?>')">
                      <img src="/assets/images/app/appGlobal/update.svg"
                      onclick="updateTasks('<?php echo $value['id'] ?>')">
                      <?php if($value['status'] == 0) {?>
                        <img src="/assets/images/app/appGlobal/conclude.svg"
                        onclick="concludeTasks('<?php echo $value['id'] ?>')">
                      <?php }?>
                    </span>
                    
                  </p>
                </article>
              
              <?php } ?>
              
            </div>
            
          </div>
        </div>
      </div>
    </section>

    <div class="newTasksArea">
      <div class="newTasksExit"></div>
      <div class="newTasksForm">
        <article class="newTasksFormTitle">
          <img src="/assets/images/app/appGlobal/iconTasksModal.svg">
          <h3>Adicionar tarefa:</h3>
        </article>
        <p></p>

        <form>
          <article class="newTasksLine">
            <label for="newTasksDec">
              <img src="/assets/images/app/appGlobal/iconDescModal.svg"> Descição:
            </label>
            <textarea type="text" id='newTasksDec'
            placeholder="Descreva a tarefa a ser realizada." name="Desc"></textarea>
          </article>

          <div class="newTasksLine">
            <article class="newTasksDate">
              <label for="newTasksDate">
                <img src="/assets/images/app/appGlobal/iconCalendarModal.svg"> Data:
              </label>
              <input type="datetime-local" id='newTasksDate'
              name="Date">
            </article>

            <article class="newTasksWallet">
              <label for="newTasksWallet">
                <img src="/assets/images/app/appGlobal/iconWalletModal.svg"> Carteira
              </label>
              <select id="newTasksWallet" name="Wallet">
                <option value="">Carteiras</option>

                <?php
                  foreach($this->view->wallets as $key => $value) { ?>
                  
                    <option value="<?php echo $value['id'] ?>">
                      <?php echo $value['wallet_name']?>
                    </option>
                  
                <?php
                  }
                ?>

              </select>
            </article>
          </div>

          <button>Lançar Tarefa</button>
        </form>
      </div>
    </div>

    <div class="updateTasksArea">
      <div class="updateTasksExit"></div>
      <div class="updateTasksForm">
        <article class="updateTasksFormTitle">
          <img src="/assets/images/app/appGlobal/iconTasksModal.svg">
          <h3>Atualizar tarefa:</h3>
        </article>
        <p></p>

        <form>
          <article class="updateTasksLine">
            <label for="updateTasksDec">
              <img src="/assets/images/app/appGlobal/iconDescModal.svg"> Descição:
            </label>
            <textarea type="text" id='updateTasksDec'
            placeholder="Descreva a tarefa a ser realizada." name="Desc"></textarea>
          </article>

          <div class="updateTasksLine">
            <article class="updateTasksDate">
              <label for="updateTasksDate">
                <img src="/assets/images/app/appGlobal/iconCalendarModal.svg"> Data:
              </label>
              <input type="datetime" id='updateTasksDate' data-mask="00/00/0000 00:00:00"
              name="Date">
            </article>

            <article class="updateTasksWallet">
              <label for="updateTasksWallet">
                <img src="/assets/images/app/appGlobal/iconWalletModal.svg"> Carteira
              </label>
              <select id="updateTasksWallet" name="Wallet">
                <option value="">Carteiras</option>

                <?php
                  foreach($this->view->wallets as $key => $value) { ?>
                  
                    <option value="<?php echo $value['id'] ?>">
                      <?php echo $value['wallet_name']?>
                    </option>
                  
                <?php
                  }
                ?>

              </select>
            </article>
          </div>

          <article class="updateTasksLine">
            <label for="updateTasksStatus">
              <img src="/assets/images/app/appGlobal/iconTitleModal.svg"> Status
            </label>
            <select id="updateTasksStatus" name="Status">
              <option value="0">Pendente</option>
              <option value="1">Concluída</option>
            </select>
          </article>

          <button>Atualizar Tarefa</button>
        </form>
      </div>
    </div>

    <!-- jQuery e JavaScript -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="/assets/js/plugin/mask/jquery.mask.js"></script>

    <script src="/assets/js/scriptAppTasks.js"></script>
  </body>
</html>
