<!DOCTYPE html>
<html>
  <head>
    <meta charset="UFT-8">
    <meta http-equiv="content-language" content="pt-br">
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta name="author" content="Claudiano Lima">
    <meta name="description" content="O Organize Pessoal é um gerenciador de 
    finanças e tarefas simples, muito poderoso e totalmente gratuito. Conte com 
    o Organize Pessoal, com ele você tem o controle de sua vida financeira e 
    pessoal.">
    <meta name="keywords" content="finanças, financeiro, controle, 
    gerenciamento de contas, gerenciamento financeiro, controle financeiro, 
    gerenciador de tarefas, controle pesoal">
    <meta name="robots" content="index, follow"> 
    <meta itemprop="name" content="Organize Pessoal - Organize sua vida de forma fácil">
    <meta itemprop="description" content="O Organize Pessoal é um gerenciador de 
    finanças e tarefas simples, muito poderoso e totalmente gratuito. Conte com 
    o Organize Pessoal, com ele você tem o controle de sua vida financeira e 
    pessoal.">
    <meta name="viewport" content="width=device-width, initial-scale=1, max-scale=1">
    
    <!-- Estilos CSS -->
    <link rel="stylesheet" type="text/css" href="/assets/css/app/styleWallet.css">
    <link rel="stylesheet" type="text/css" href="/assets/css/styleGeral.css">
    <link rel="stylesheet" type="text/css" href="/assets/css/app/global/styleGlobal.css">

    <!-- Script Chart.js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js" 
    integrity="sha256-R4pqcOYV8lt7snxMQO/HSbVCFRPMdrhAFMH+vr9giYI=" 
    crossorigin="anonymous"></script>
    
    <!-- Icon -->
    <link rel='icon' type="img/svg" href="/assets/images/iconLogo.svg">
    <title>Organize Pessoal - Carteira</title>
  </head>
  <body onload = graphic()>
    <!-- loading -->
    <?php $this->importViews('loading') ?>
  
    <!-- Header -->
    <?php $this->importViews('header-app') ?>

    <section>
      <div class="containerApp">
        <div class="sectionAppArea">
          <?php $this->importViews('menu-app', 'Wallet') ?>

          <div class="sectionAppAreaRight">
            <div class="sectionAppWalletAreaGlobal">
              <div class="sectionAppNewWallet">
                <article>
                  <h3>Adicionar Carteira</h3>
                </article>
                <form>
                  <input type="text" name="newWallet" 
                  placeholder="Minha casa / Minha empresa / Meu cartão">
                  <button type="submit">
                    <img src="/assets/images/app/wallet/buttonSubmit.svg">
                  </button>
                </form>
              </div>
              <div class="sectionAppWallets">
                <?php $this->importViews('appWallet', 'Receive') ?>
              </div>
            </div>

            <p id='messegeWallet'></p>
            
            <div class="appWalletsCardsArea">

              <?php 
              foreach ($this->view->dataSumWallets as $key => $value) { 
                $sumReceive = $value['sumReceive'];
                $sumExpenses = $value['sumExpenses'];
              ?>

                <div class="appWalletCard">
                  <img class="iconWalletRemove"
                  src="/assets/images/app/wallet/buttonRemove.svg"
                  onclick="removeWallet('<?php echo $value['id']?>')">
                  <img class='iconWalletCard' 
                  src="/assets/images/app/wallet/iconWallet.svg">
                  <article>
                    <h4 class="titleWallet"><?php echo $value['walletName']?></h4>
                    <!-- Saldo -->
                    <p class="saleWallet"> 
                      Saldo R$
                      <?php echo(bcsub($sumReceive, $sumExpenses, 2));?>
                    </p>
                    <!-- Receita-->
                    <p class="receiveWallet">
                      Receitas: R$
                      <?php echo number_format($sumReceive,2,',','.'); ?>
                    </p>
                    <!-- Despesas -->
                    <p class="expenseWallet">
                      Despesas: R$
                      <?php echo number_format($sumExpenses,2,',','.'); ?>
                    </p>
                  </article>
                </div>

              <?php } ?>

            </div>


          </div>
        </div>
        <div class="graphicWalletMessenger">
          <h3>
            Caso o gráfico esteja de difícil visualização, por favor 
            rotacionar a tela do seu celular!
          </h3>
        </div>
        <div class="graphicWalletArea">
          <div class="graphicWallet">
            <canvas id='GraphicWallet'></canvas>
          </div>
        </div>
      </div>
    </section>

    <!-- jQuery e JavaScript -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="/assets/js/scriptAppWallet.js"></script>
  </body>
</html>
