<link rel="stylesheet" type="text/css" href="/assets/css/app/styleAppWallet.css">
<div class='sectionAppWalletArea'>
  <div class="sectionAppWallet">
    <div class="sectionAppWalletIcon">
      <img src="/assets/images/app/home/header/walletIcon.svg">
    </div>
    <div class="sectionAppWalletInfo">
      <h4 class="carteira">Carteiras</h4>
    </div>
  </div>
  <div class="MinhasCarteiras">
    <ul>
      <li class="carteiraSelect">Minha carteira</li>
    </ul>
  </div>
</div>


<!-- jQuery e JavaScript -->
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="/assets/js/scriptAppWalletGlobal.js"></script>