<link rel="stylesheet" type="text/css" href="/assets/css/app/styleAppWallet.css">
<div class='sectionAppWalletArea'>
  <div class="sectionAppWallet">
    <div class="sectionAppWalletIcon">
      <img src="/assets/images/app/home/header/walletIcon.svg">
    </div>
    <div class="sectionAppWalletInfo">
      <?php foreach($this->view->wallets as $key => $value) { 
        if($value['id'] === $_SESSION['userWallet']) {?>
        
        <h4 class="carteira">
          <?php echo $value['wallet_name'] ?>
        </h4>

        <?php }
      } ?>
    </div>
  </div>
  <div class="MinhasCarteiras">
    <ul>
    <?php
    foreach($this->view->wallets as $key => $value) { ?>    
      <li class="carteiraSelect" 
      onclick="walletSelect('<?php echo $value['id']?>')">
        <?php echo $value['wallet_name'] ?>
      </li>
    <?php
    }
    ?>
      
    </ul>
  </div>
</div>


<!-- jQuery e JavaScript -->
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="/assets/js/scriptAppWalletGlobal.js"></script>