<link rel="stylesheet" type="text/css" href="/assets/css/home/styleFooter.css">
<footer>
  <section class="container" data-anime='depth'>
    <div class="footerContent">
      <article class="footerItem">
        Sobre:
        <p class="footerItemDesc">
          O organize pessoal é um gerenciador de contas e tarefas simples, 
          poderoso e gratuito. Surgiu com a ideia de organizar tudo em um só 
          local, não só a suas contas mas também as suas tarefas cotidianas.
        </p>
      </article>

      <article class="footerItem">
        Contato:
        <div class="footerItemDesc">
          <h4 class="email">Email:</h4>
          <p>
            claudianoplima@hotmail.com
          </p>
          <h4 class="github">Github:</h4>
          <p>
            <a href="https://github.com/claudianopl">
              github.com/claudianopl
            </a>
          </p>
          <h4 class="linkedin">Linkedin:</h4>
          <p>
            <a href="https://linkedin.com/in/claudianopl">
              linkedin.com/in/claudianopl
            </a>
          </p>
        </div>
      </article>

      <article class="footerItem">
        Créditos:
        <p class="footerItemDesc">
          O organize pessoal foi desenvolvido por Claudiano Lima, com o 
          intuito de ajudar as pessoas com uma ferramenta excelente de 
          gerenciamento de finanças e tarefas. Além disso, tinha o intuito 
          de treinar os conhecimentos adquiridos em desenvolvimento web.
        </p>
      </article>
    </div>
  </section>
</footer>