<!-- Estilos CSS -->
<link rel="stylesheet" type="text/css" href="/assets/css/app/styleHeaderApp.css">
<header class='headerAppHeader'>
  <div class="container">
    <div class="headerApp">
      <div class="headerAppLogo">
        <a href="/app"><img src="/assets/images/app/headerApp/logo.svg"></a>
      </div>   
      <div class="headerAppCalender">
        
      </div>
      <div class="headerAppUser">
        <img src="/assets/images/app/headerApp/user.svg"> <h4>Seu nome-PHP</h4>
      </div>
    </div>
  </div>
</header>