<!-- Estilos CSS -->
<link rel="stylesheet" type="text/css" href="/assets/css/app/styleHeaderApp.css">
<header class='headerAppHeader'>
  <div class="container">
    <div class="headerApp">
      <div class="headerAppLogo">
        <a href="/app"><img src="/assets/images/app/headerApp/logo.svg"></a>
      </div>   
      <div class="headerAppCalendarArea">

        
          <div class="monthSelectActive">
            <h4></h4><img src="/assets/images/app/headerApp/dropDownCalendar.svg">
          </div>
          
          <div class="appCalendar">
            <header>
              <h2 class="year"></h2>
              <a class="ButtonPrevious"><</a>
              <a class="ButtonNext">></a>
            </header>
            <table class="month">
              <tbody>
                <tr>
                  <td class="monthSelect">Jan</td>
                  <td class="monthSelect">Fev</td>
                  <td class="monthSelect">Mar</td>
                  <td class="monthSelect">Abr</td>
                </tr>
                <tr>
                  <td class="monthSelect">Mai</td>
                  <td class="monthSelect">Jun</td>
                  <td class="monthSelect">Jul</td>
                  <td class="monthSelect" >Ago</td>
                </tr>
                <tr>
                  <td class="monthSelect" >Set</td>
                  <td class="monthSelect" >Out</td>
                  <td class="monthSelect" >Nov</td>
                  <td class="monthSelect" >Dez</td>
                </tr>
              </tbody>
            </table>
          </div>



      </div>
      <div class="headerAppUser">
        <h4>Seu nome-PHP</h4>
      </div>
    </div>
  </div>
  <!-- jQuery e JavaScript -->
  <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
  <script src="/assets/js/scriptAppHeader.js"></script>
</header>
