<link rel="stylesheet" type="text/css" href="/assets/css/app/styleMenu.css">
<div class="sectionAppMenu">
  <nav class="sectionAppMenuNav">
    <ul>
      <a href="/app"><li class='<?php if($info == 'Home') {echo 'active';} ?>'>
        <img src="/assets/images/app/nav/iconHome.svg"> Home
      </li></a>
      <a href="/app/receitas"><li class='<?php if($info == 'Receive') {echo 'active';}?>'>
        <img src="/assets/images/app/nav/iconReceitas.svg"> Receitas
      </li></a>
      <a href="/app/despesas"><li class='<?php if($info == 'Despesas') {echo 'active';}?>'>
        <img src="/assets/images/app/nav/iconDespesas.svg"> Despesas
      </li></a>
      <a href="/app/tarefas"><li class='<?php if($info == 'Tarefas') {echo 'active';}?>'>
        <img src="/assets/images/app/nav/iconTarefas.svg"> Tarefas a fazerem
      </li></a>
      <a href="/app/fixas"><li class='<?php if($info == 'Fixas') {echo 'active';}?>'>
        <img src="/assets/images/app/nav/iconFixas.svg"> Fixas
      </li></a>
      <a href="/app/carteira"><li class='<?php if($info == 'Carteira') {echo 'active';}?>'>
        <img src="/assets/images/app/nav/iconCarteira.svg"> Carteira
      </li></a>
      <a href="/app/perfil"><li class='<?php if($info == 'Perfil') {echo 'active';}?>'>
        <img src="/assets/images/app/nav/iconPerfil.svg"> Perfil
      </li></a>
      <a href="/"><li class='navAnimate'>
        <img src="/assets/images/app/nav/iconSair.svg"> Sair
      </li></a>
    </ul>
  </nav>
</div>

<input id="menuHamburguer" type="checkbox">
	  <label for="menuHamburguer">
	    <div class="menuMobile">
	      <span class="hamburguer"></span>
	    </div>
	  </label>
    <nav class="navMenu">
      <ul>
        <a href="/app"><li class='<?php if($info == 'Home') {echo 'active';} ?>'>
          <img src="/assets/images/app/nav/iconHome.svg"> Home
        </li></a>
        <a href="/app/receitas"><li class='<?php if($info == 'Receitas') {echo 'active';}?>'>
          <img src="/assets/images/app/nav/iconReceitas.svg"> Receitas
        </li></a>
        <a href="/app/despesas"><li class='<?php if($info == 'Despesas') {echo 'active';}?>'>
          <img src="/assets/images/app/nav/iconDespesas.svg"> Despesas
        </li></a>
        <a href="/app/tarefas"><li class='<?php if($info == 'Tarefas') {echo 'active';}?>'>
          <img src="/assets/images/app/nav/iconTarefas.svg"> Tarefas a fazerem
        </li></a>
        <a href="/app/fixas"><li class='<?php if($info == 'Fixas') {echo 'active';}?>'>
          <img src="/assets/images/app/nav/iconFixas.svg"> Fixas
        </li></a>
        <a href="/app/carteira"><li class='<?php if($info == 'Carteira') {echo 'active';}?>'>
          <img src="/assets/images/app/nav/iconCarteira.svg"> Carteira
        </li></a>
        <a href="/app/perfil"><li class='<?php if($info == 'Perfil') {echo 'active';}?>'>
          <img src="/assets/images/app/nav/iconPerfil.svg"> Perfil
        </li></a>
        <a href="/"><li>
          <img src="/assets/images/app/nav/iconSair.svg"> Sair
        </li></a>
      </ul>
  </nav>