<header>
  <div class="header">
    <div class='logo'>
      <img src='assets/images/logo.svg'>
    </div>
    <div class='menu'>
      <nav>
        <ul class='teste'>
          <li class='active'><a href="">Home</a></li>
          <li><a href="">Sobre</a></li>
          <li><a href="">Cadastre-se</a></li>
          <li class="ultimo"><a href="">Login</a></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

  
