<header>
  <div class="header">
    <div class='logo'>
      <img src='assets/images/logo.svg'>
    </div>
    <div class='menu'>
      <nav>
        <ul class='teste'>
          <li class='<?php if($info == 'Home'){echo'active';} ?>'>
            <a href="/home">Home</a>
          </li>
          <li class='<?php if($info == 'Sobre'){echo'active';} ?>'>
            <a href="/sobre">Sobre</a>
          </li>
          <li class='<?php if($info == 'Cadastre-se'){echo'active';} ?>'>
            <a href="/cadastre-se">Cadastre-se</a>
          </li>
          <li class='<?php if($info == 'Login'){echo'active';} ?>'>
            <a href="/login">Login</a>
          </li>
        </ul>
      </nav>
    </div>
  </div>
</header>
