<!-- Estilos CSS -->
<link rel="stylesheet" type="text/css" href="/assets/css/app/styleHeaderApp.css">
<header>
  <div class="container">
    <div class="headerApp">
      <div class="headerAppLogo">
        <a href="/app"><img src="/assets/images/app/headerApp/logo.svg"></a>
      </div>
      <?php if($info == 'Home') {?>
        
        <div class="headerAppCalender">
          
        </div>

      <?php } ?>
      <div class="headerAppUser">
        <img src="/assets/images/app/headerApp/user.svg"> <h4>Seu nome-PHP</h4>
      </div>
    </div>
  </div>
</header>