<link rel="stylesheet" type="text/css" href="/assets/css/styleHeader.css">
<header>
  <div class="header">
    <div class='logo' data-anime='left'>
      <img src='assets/images/logo.svg'>
    </div>
    <div class='menu'>
      <img class='menuMobile' src='assets/images/menuOpen.svg' onclick='toggleMenu()'>
      <nav id='menu' data-anime='menu'>
        <ul>
          <li class='<?php if($info == 'Home'){echo'active';} ?>'>
            <a href="/">Home</a>
          </li>
          <li class='<?php if($info == 'Sobre'){echo'active';} ?>'>
            <a href="/sobre">Sobre</a>
          </li>
          <li class='<?php if($info == 'Cadastre-se'){echo'active';} ?>'>
            <a href="/cadastre-se">Cadastre-se</a>
          </li>
          <li class='<?php if($info == 'Login'){echo'active';} ?>'>
            <a href="/login">Login</a>
          </li>
        </ul>
      </nav>
    </div>
  </div>
</header>
